// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/audio_to_tensor_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/audio_to_tensor_calculator.proto</summary>
  public static partial class AudioToTensorCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/audio_to_tensor_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudioToTensorCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CmFQYWNrYWdlcy9jb20uZGF0ZWE4My5tZWRpYXBpcGVmb3Jkb3RzL1J1bnRp",
            "bWUvQ2FsY3VsYXRvcnMvdGVuc29yL2F1ZGlvX3RvX3RlbnNvcl9jYWxjdWxh",
            "dG9yLnByb3RvEgltZWRpYXBpcGUaSFBhY2thZ2VzL2NvbS5kYXRlYTgzLm1l",
            "ZGlhcGlwZWZvcmRvdHMvUnVudGltZS9GcmFtZXdvcmsvY2FsY3VsYXRvci5w",
            "cm90byLFBgoeQXVkaW9Ub1RlbnNvckNhbGN1bGF0b3JPcHRpb25zEhQKDG51",
            "bV9jaGFubmVscxgBIAEoAxITCgtudW1fc2FtcGxlcxgCIAEoAxIiChdudW1f",
            "b3ZlcmxhcHBpbmdfc2FtcGxlcxgDIAEoAzoBMBIaChJ0YXJnZXRfc2FtcGxl",
            "X3JhdGUYBCABKAESGQoLc3RyZWFtX21vZGUYBSABKAg6BHRydWUSKwodY2hl",
            "Y2tfaW5jb25zaXN0ZW50X3RpbWVzdGFtcHMYBiABKAg6BHRydWUSEAoIZmZ0",
            "X3NpemUYByABKAMSHgoWcGFkZGluZ19zYW1wbGVzX2JlZm9yZRgIIAEoAxId",
            "ChVwYWRkaW5nX3NhbXBsZXNfYWZ0ZXIYCSABKAMSZQoKZmx1c2hfbW9kZRgK",
            "IAEoDjIzLm1lZGlhcGlwZS5BdWRpb1RvVGVuc29yQ2FsY3VsYXRvck9wdGlv",
            "bnMuRmx1c2hNb2RlOhxFTlRJUkVfVEFJTF9BVF9USU1FU1RBTVBfTUFYEmIK",
            "EWRmdF90ZW5zb3JfZm9ybWF0GAsgASgOMjkubWVkaWFwaXBlLkF1ZGlvVG9U",
            "ZW5zb3JDYWxjdWxhdG9yT3B0aW9ucy5EZnRUZW5zb3JGb3JtYXQ6DFdJVEhf",
            "TllRVUlTVBIWCg52b2x1bWVfZ2Fpbl9kYhgMIAEoARIaChJzb3VyY2Vfc2Ft",
            "cGxlX3JhdGUYDSABKAEiTQoJRmx1c2hNb2RlEggKBE5PTkUQABIgChxFTlRJ",
            "UkVfVEFJTF9BVF9USU1FU1RBTVBfTUFYEAESFAoQUFJPQ0VFRF9BU19VU1VB",
            "TBACIncKD0RmdFRlbnNvckZvcm1hdBIdChlERlRfVEVOU09SX0ZPUk1BVF9V",
            "TktOT1dOEAASGgoWV0lUSE9VVF9EQ19BTkRfTllRVUlTVBABEhAKDFdJVEhf",
            "TllRVUlTVBACEhcKE1dJVEhfRENfQU5EX05ZUVVJU1QQAzJYCgNleHQSHC5t",
            "ZWRpYXBpcGUuQ2FsY3VsYXRvck9wdGlvbnMYuMH21QEgASgLMikubWVkaWFw",
            "aXBlLkF1ZGlvVG9UZW5zb3JDYWxjdWxhdG9yT3B0aW9ucw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.AudioToTensorCalculatorOptions), global::Mediapipe.AudioToTensorCalculatorOptions.Parser, new[]{ "NumChannels", "NumSamples", "NumOverlappingSamples", "TargetSampleRate", "StreamMode", "CheckInconsistentTimestamps", "FftSize", "PaddingSamplesBefore", "PaddingSamplesAfter", "FlushMode", "DftTensorFormat", "VolumeGainDb", "SourceSampleRate" }, null, new[]{ typeof(global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode), typeof(global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat) }, new pb::Extension[] { global::Mediapipe.AudioToTensorCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioToTensorCalculatorOptions : pb::IMessage<AudioToTensorCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioToTensorCalculatorOptions> _parser = new pb::MessageParser<AudioToTensorCalculatorOptions>(() => new AudioToTensorCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioToTensorCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.AudioToTensorCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioToTensorCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioToTensorCalculatorOptions(AudioToTensorCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      numChannels_ = other.numChannels_;
      numSamples_ = other.numSamples_;
      numOverlappingSamples_ = other.numOverlappingSamples_;
      targetSampleRate_ = other.targetSampleRate_;
      streamMode_ = other.streamMode_;
      checkInconsistentTimestamps_ = other.checkInconsistentTimestamps_;
      fftSize_ = other.fftSize_;
      paddingSamplesBefore_ = other.paddingSamplesBefore_;
      paddingSamplesAfter_ = other.paddingSamplesAfter_;
      flushMode_ = other.flushMode_;
      dftTensorFormat_ = other.dftTensorFormat_;
      volumeGainDb_ = other.volumeGainDb_;
      sourceSampleRate_ = other.sourceSampleRate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioToTensorCalculatorOptions Clone() {
      return new AudioToTensorCalculatorOptions(this);
    }

    /// <summary>Field number for the "num_channels" field.</summary>
    public const int NumChannelsFieldNumber = 1;
    private readonly static long NumChannelsDefaultValue = 0L;

    private long numChannels_;
    /// <summary>
    /// The required number of channels the output audio tensor has.
    /// If set to 1, multichannel signals will be automatically mixed down to mono.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NumChannels {
      get { if ((_hasBits0 & 1) != 0) { return numChannels_; } else { return NumChannelsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        numChannels_ = value;
      }
    }
    /// <summary>Gets whether the "num_channels" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumChannels {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "num_channels" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumChannels() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "num_samples" field.</summary>
    public const int NumSamplesFieldNumber = 2;
    private readonly static long NumSamplesDefaultValue = 0L;

    private long numSamples_;
    /// <summary>
    /// The required number of samples per channel the output audio tensor has.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NumSamples {
      get { if ((_hasBits0 & 2) != 0) { return numSamples_; } else { return NumSamplesDefaultValue; } }
      set {
        _hasBits0 |= 2;
        numSamples_ = value;
      }
    }
    /// <summary>Gets whether the "num_samples" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumSamples {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "num_samples" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumSamples() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "num_overlapping_samples" field.</summary>
    public const int NumOverlappingSamplesFieldNumber = 3;
    private readonly static long NumOverlappingSamplesDefaultValue = 0L;

    private long numOverlappingSamples_;
    /// <summary>
    /// The number of overlapping samples per channel the output audio tensor has.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NumOverlappingSamples {
      get { if ((_hasBits0 & 4) != 0) { return numOverlappingSamples_; } else { return NumOverlappingSamplesDefaultValue; } }
      set {
        _hasBits0 |= 4;
        numOverlappingSamples_ = value;
      }
    }
    /// <summary>Gets whether the "num_overlapping_samples" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumOverlappingSamples {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "num_overlapping_samples" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumOverlappingSamples() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "target_sample_rate" field.</summary>
    public const int TargetSampleRateFieldNumber = 4;
    private readonly static double TargetSampleRateDefaultValue = 0D;

    private double targetSampleRate_;
    /// <summary>
    /// The target number of samples per second (hertz) of the audio buffers that
    /// will be converted into tensors.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TargetSampleRate {
      get { if ((_hasBits0 & 8) != 0) { return targetSampleRate_; } else { return TargetSampleRateDefaultValue; } }
      set {
        _hasBits0 |= 8;
        targetSampleRate_ = value;
      }
    }
    /// <summary>Gets whether the "target_sample_rate" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTargetSampleRate {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "target_sample_rate" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTargetSampleRate() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "stream_mode" field.</summary>
    public const int StreamModeFieldNumber = 5;
    private readonly static bool StreamModeDefaultValue = true;

    private bool streamMode_;
    /// <summary>
    /// Whether to treat the input audio stream as a continuous stream or a batch
    /// of unrelated audio buffers.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool StreamMode {
      get { if ((_hasBits0 & 16) != 0) { return streamMode_; } else { return StreamModeDefaultValue; } }
      set {
        _hasBits0 |= 16;
        streamMode_ = value;
      }
    }
    /// <summary>Gets whether the "stream_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStreamMode {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "stream_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStreamMode() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "check_inconsistent_timestamps" field.</summary>
    public const int CheckInconsistentTimestampsFieldNumber = 6;
    private readonly static bool CheckInconsistentTimestampsDefaultValue = true;

    private bool checkInconsistentTimestamps_;
    /// <summary>
    /// Set to false to disable checks for jitter in timestamp values. Useful with
    /// live audio input.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CheckInconsistentTimestamps {
      get { if ((_hasBits0 & 32) != 0) { return checkInconsistentTimestamps_; } else { return CheckInconsistentTimestampsDefaultValue; } }
      set {
        _hasBits0 |= 32;
        checkInconsistentTimestamps_ = value;
      }
    }
    /// <summary>Gets whether the "check_inconsistent_timestamps" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCheckInconsistentTimestamps {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "check_inconsistent_timestamps" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCheckInconsistentTimestamps() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "fft_size" field.</summary>
    public const int FftSizeFieldNumber = 7;
    private readonly static long FftSizeDefaultValue = 0L;

    private long fftSize_;
    /// <summary>
    /// Size of the fft in number of bins. If set, the calculator outputs fft
    /// tensors.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FftSize {
      get { if ((_hasBits0 & 64) != 0) { return fftSize_; } else { return FftSizeDefaultValue; } }
      set {
        _hasBits0 |= 64;
        fftSize_ = value;
      }
    }
    /// <summary>Gets whether the "fft_size" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFftSize {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "fft_size" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFftSize() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "padding_samples_before" field.</summary>
    public const int PaddingSamplesBeforeFieldNumber = 8;
    private readonly static long PaddingSamplesBeforeDefaultValue = 0L;

    private long paddingSamplesBefore_;
    /// <summary>
    /// The amount of padding samples to add before the audio after resampling.
    /// Note that the timestamps shift. Currently, only zero padding is supported.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PaddingSamplesBefore {
      get { if ((_hasBits0 & 128) != 0) { return paddingSamplesBefore_; } else { return PaddingSamplesBeforeDefaultValue; } }
      set {
        _hasBits0 |= 128;
        paddingSamplesBefore_ = value;
      }
    }
    /// <summary>Gets whether the "padding_samples_before" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPaddingSamplesBefore {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "padding_samples_before" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPaddingSamplesBefore() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "padding_samples_after" field.</summary>
    public const int PaddingSamplesAfterFieldNumber = 9;
    private readonly static long PaddingSamplesAfterDefaultValue = 0L;

    private long paddingSamplesAfter_;
    /// <summary>
    /// The amount of padding samples to add after the audio after resampling.
    /// Currently, only zero padding is supported.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PaddingSamplesAfter {
      get { if ((_hasBits0 & 256) != 0) { return paddingSamplesAfter_; } else { return PaddingSamplesAfterDefaultValue; } }
      set {
        _hasBits0 |= 256;
        paddingSamplesAfter_ = value;
      }
    }
    /// <summary>Gets whether the "padding_samples_after" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPaddingSamplesAfter {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "padding_samples_after" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPaddingSamplesAfter() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "flush_mode" field.</summary>
    public const int FlushModeFieldNumber = 10;
    private readonly static global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode FlushModeDefaultValue = global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode.EntireTailAtTimestampMax;

    private global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode flushMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode FlushMode {
      get { if ((_hasBits0 & 512) != 0) { return flushMode_; } else { return FlushModeDefaultValue; } }
      set {
        _hasBits0 |= 512;
        flushMode_ = value;
      }
    }
    /// <summary>Gets whether the "flush_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFlushMode {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "flush_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFlushMode() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "dft_tensor_format" field.</summary>
    public const int DftTensorFormatFieldNumber = 11;
    private readonly static global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat DftTensorFormatDefaultValue = global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat.WithNyquist;

    private global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat dftTensorFormat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat DftTensorFormat {
      get { if ((_hasBits0 & 1024) != 0) { return dftTensorFormat_; } else { return DftTensorFormatDefaultValue; } }
      set {
        _hasBits0 |= 1024;
        dftTensorFormat_ = value;
      }
    }
    /// <summary>Gets whether the "dft_tensor_format" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDftTensorFormat {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "dft_tensor_format" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDftTensorFormat() {
      _hasBits0 &= ~1024;
    }

    /// <summary>Field number for the "volume_gain_db" field.</summary>
    public const int VolumeGainDbFieldNumber = 12;
    private readonly static double VolumeGainDbDefaultValue = 0D;

    private double volumeGainDb_;
    /// <summary>
    /// The volume gain, measured in dB.
    /// Scale the input audio amplitude by 10^(volume_gain_db/20).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double VolumeGainDb {
      get { if ((_hasBits0 & 2048) != 0) { return volumeGainDb_; } else { return VolumeGainDbDefaultValue; } }
      set {
        _hasBits0 |= 2048;
        volumeGainDb_ = value;
      }
    }
    /// <summary>Gets whether the "volume_gain_db" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolumeGainDb {
      get { return (_hasBits0 & 2048) != 0; }
    }
    /// <summary>Clears the value of the "volume_gain_db" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolumeGainDb() {
      _hasBits0 &= ~2048;
    }

    /// <summary>Field number for the "source_sample_rate" field.</summary>
    public const int SourceSampleRateFieldNumber = 13;
    private readonly static double SourceSampleRateDefaultValue = 0D;

    private double sourceSampleRate_;
    /// <summary>
    /// The source number of samples per second (hertz) of the input audio buffers.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SourceSampleRate {
      get { if ((_hasBits0 & 4096) != 0) { return sourceSampleRate_; } else { return SourceSampleRateDefaultValue; } }
      set {
        _hasBits0 |= 4096;
        sourceSampleRate_ = value;
      }
    }
    /// <summary>Gets whether the "source_sample_rate" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSourceSampleRate {
      get { return (_hasBits0 & 4096) != 0; }
    }
    /// <summary>Clears the value of the "source_sample_rate" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSourceSampleRate() {
      _hasBits0 &= ~4096;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioToTensorCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioToTensorCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumChannels != other.NumChannels) return false;
      if (NumSamples != other.NumSamples) return false;
      if (NumOverlappingSamples != other.NumOverlappingSamples) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TargetSampleRate, other.TargetSampleRate)) return false;
      if (StreamMode != other.StreamMode) return false;
      if (CheckInconsistentTimestamps != other.CheckInconsistentTimestamps) return false;
      if (FftSize != other.FftSize) return false;
      if (PaddingSamplesBefore != other.PaddingSamplesBefore) return false;
      if (PaddingSamplesAfter != other.PaddingSamplesAfter) return false;
      if (FlushMode != other.FlushMode) return false;
      if (DftTensorFormat != other.DftTensorFormat) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(VolumeGainDb, other.VolumeGainDb)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SourceSampleRate, other.SourceSampleRate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasNumChannels) hash ^= NumChannels.GetHashCode();
      if (HasNumSamples) hash ^= NumSamples.GetHashCode();
      if (HasNumOverlappingSamples) hash ^= NumOverlappingSamples.GetHashCode();
      if (HasTargetSampleRate) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TargetSampleRate);
      if (HasStreamMode) hash ^= StreamMode.GetHashCode();
      if (HasCheckInconsistentTimestamps) hash ^= CheckInconsistentTimestamps.GetHashCode();
      if (HasFftSize) hash ^= FftSize.GetHashCode();
      if (HasPaddingSamplesBefore) hash ^= PaddingSamplesBefore.GetHashCode();
      if (HasPaddingSamplesAfter) hash ^= PaddingSamplesAfter.GetHashCode();
      if (HasFlushMode) hash ^= FlushMode.GetHashCode();
      if (HasDftTensorFormat) hash ^= DftTensorFormat.GetHashCode();
      if (HasVolumeGainDb) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(VolumeGainDb);
      if (HasSourceSampleRate) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SourceSampleRate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasNumChannels) {
        output.WriteRawTag(8);
        output.WriteInt64(NumChannels);
      }
      if (HasNumSamples) {
        output.WriteRawTag(16);
        output.WriteInt64(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        output.WriteRawTag(24);
        output.WriteInt64(NumOverlappingSamples);
      }
      if (HasTargetSampleRate) {
        output.WriteRawTag(33);
        output.WriteDouble(TargetSampleRate);
      }
      if (HasStreamMode) {
        output.WriteRawTag(40);
        output.WriteBool(StreamMode);
      }
      if (HasCheckInconsistentTimestamps) {
        output.WriteRawTag(48);
        output.WriteBool(CheckInconsistentTimestamps);
      }
      if (HasFftSize) {
        output.WriteRawTag(56);
        output.WriteInt64(FftSize);
      }
      if (HasPaddingSamplesBefore) {
        output.WriteRawTag(64);
        output.WriteInt64(PaddingSamplesBefore);
      }
      if (HasPaddingSamplesAfter) {
        output.WriteRawTag(72);
        output.WriteInt64(PaddingSamplesAfter);
      }
      if (HasFlushMode) {
        output.WriteRawTag(80);
        output.WriteEnum((int) FlushMode);
      }
      if (HasDftTensorFormat) {
        output.WriteRawTag(88);
        output.WriteEnum((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        output.WriteRawTag(97);
        output.WriteDouble(VolumeGainDb);
      }
      if (HasSourceSampleRate) {
        output.WriteRawTag(105);
        output.WriteDouble(SourceSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasNumChannels) {
        output.WriteRawTag(8);
        output.WriteInt64(NumChannels);
      }
      if (HasNumSamples) {
        output.WriteRawTag(16);
        output.WriteInt64(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        output.WriteRawTag(24);
        output.WriteInt64(NumOverlappingSamples);
      }
      if (HasTargetSampleRate) {
        output.WriteRawTag(33);
        output.WriteDouble(TargetSampleRate);
      }
      if (HasStreamMode) {
        output.WriteRawTag(40);
        output.WriteBool(StreamMode);
      }
      if (HasCheckInconsistentTimestamps) {
        output.WriteRawTag(48);
        output.WriteBool(CheckInconsistentTimestamps);
      }
      if (HasFftSize) {
        output.WriteRawTag(56);
        output.WriteInt64(FftSize);
      }
      if (HasPaddingSamplesBefore) {
        output.WriteRawTag(64);
        output.WriteInt64(PaddingSamplesBefore);
      }
      if (HasPaddingSamplesAfter) {
        output.WriteRawTag(72);
        output.WriteInt64(PaddingSamplesAfter);
      }
      if (HasFlushMode) {
        output.WriteRawTag(80);
        output.WriteEnum((int) FlushMode);
      }
      if (HasDftTensorFormat) {
        output.WriteRawTag(88);
        output.WriteEnum((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        output.WriteRawTag(97);
        output.WriteDouble(VolumeGainDb);
      }
      if (HasSourceSampleRate) {
        output.WriteRawTag(105);
        output.WriteDouble(SourceSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasNumChannels) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumChannels);
      }
      if (HasNumSamples) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumOverlappingSamples);
      }
      if (HasTargetSampleRate) {
        size += 1 + 8;
      }
      if (HasStreamMode) {
        size += 1 + 1;
      }
      if (HasCheckInconsistentTimestamps) {
        size += 1 + 1;
      }
      if (HasFftSize) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FftSize);
      }
      if (HasPaddingSamplesBefore) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PaddingSamplesBefore);
      }
      if (HasPaddingSamplesAfter) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PaddingSamplesAfter);
      }
      if (HasFlushMode) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FlushMode);
      }
      if (HasDftTensorFormat) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        size += 1 + 8;
      }
      if (HasSourceSampleRate) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioToTensorCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasNumChannels) {
        NumChannels = other.NumChannels;
      }
      if (other.HasNumSamples) {
        NumSamples = other.NumSamples;
      }
      if (other.HasNumOverlappingSamples) {
        NumOverlappingSamples = other.NumOverlappingSamples;
      }
      if (other.HasTargetSampleRate) {
        TargetSampleRate = other.TargetSampleRate;
      }
      if (other.HasStreamMode) {
        StreamMode = other.StreamMode;
      }
      if (other.HasCheckInconsistentTimestamps) {
        CheckInconsistentTimestamps = other.CheckInconsistentTimestamps;
      }
      if (other.HasFftSize) {
        FftSize = other.FftSize;
      }
      if (other.HasPaddingSamplesBefore) {
        PaddingSamplesBefore = other.PaddingSamplesBefore;
      }
      if (other.HasPaddingSamplesAfter) {
        PaddingSamplesAfter = other.PaddingSamplesAfter;
      }
      if (other.HasFlushMode) {
        FlushMode = other.FlushMode;
      }
      if (other.HasDftTensorFormat) {
        DftTensorFormat = other.DftTensorFormat;
      }
      if (other.HasVolumeGainDb) {
        VolumeGainDb = other.VolumeGainDb;
      }
      if (other.HasSourceSampleRate) {
        SourceSampleRate = other.SourceSampleRate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NumChannels = input.ReadInt64();
            break;
          }
          case 16: {
            NumSamples = input.ReadInt64();
            break;
          }
          case 24: {
            NumOverlappingSamples = input.ReadInt64();
            break;
          }
          case 33: {
            TargetSampleRate = input.ReadDouble();
            break;
          }
          case 40: {
            StreamMode = input.ReadBool();
            break;
          }
          case 48: {
            CheckInconsistentTimestamps = input.ReadBool();
            break;
          }
          case 56: {
            FftSize = input.ReadInt64();
            break;
          }
          case 64: {
            PaddingSamplesBefore = input.ReadInt64();
            break;
          }
          case 72: {
            PaddingSamplesAfter = input.ReadInt64();
            break;
          }
          case 80: {
            FlushMode = (global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode) input.ReadEnum();
            break;
          }
          case 88: {
            DftTensorFormat = (global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat) input.ReadEnum();
            break;
          }
          case 97: {
            VolumeGainDb = input.ReadDouble();
            break;
          }
          case 105: {
            SourceSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NumChannels = input.ReadInt64();
            break;
          }
          case 16: {
            NumSamples = input.ReadInt64();
            break;
          }
          case 24: {
            NumOverlappingSamples = input.ReadInt64();
            break;
          }
          case 33: {
            TargetSampleRate = input.ReadDouble();
            break;
          }
          case 40: {
            StreamMode = input.ReadBool();
            break;
          }
          case 48: {
            CheckInconsistentTimestamps = input.ReadBool();
            break;
          }
          case 56: {
            FftSize = input.ReadInt64();
            break;
          }
          case 64: {
            PaddingSamplesBefore = input.ReadInt64();
            break;
          }
          case 72: {
            PaddingSamplesAfter = input.ReadInt64();
            break;
          }
          case 80: {
            FlushMode = (global::Mediapipe.AudioToTensorCalculatorOptions.Types.FlushMode) input.ReadEnum();
            break;
          }
          case 88: {
            DftTensorFormat = (global::Mediapipe.AudioToTensorCalculatorOptions.Types.DftTensorFormat) input.ReadEnum();
            break;
          }
          case 97: {
            VolumeGainDb = input.ReadDouble();
            break;
          }
          case 105: {
            SourceSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AudioToTensorCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Determines the "flushing" behavior in stream mode.
      /// </summary>
      public enum FlushMode {
        /// <summary>
        /// Unspecified (causes an error). Won't be used because of the default.
        /// </summary>
        [pbr::OriginalName("NONE")] None = 0,
        /// <summary>
        /// Emit a packet with the entire remainder at `Timestamp::Max`.
        /// </summary>
        [pbr::OriginalName("ENTIRE_TAIL_AT_TIMESTAMP_MAX")] EntireTailAtTimestampMax = 1,
        /// <summary>
        /// Continue emitting framed packets with relevant timestamps.
        /// </summary>
        [pbr::OriginalName("PROCEED_AS_USUAL")] ProceedAsUsual = 2,
      }

      public enum DftTensorFormat {
        [pbr::OriginalName("DFT_TENSOR_FORMAT_UNKNOWN")] Unknown = 0,
        /// <summary>
        /// The output dft tensor without dc and nyquist components.
        /// </summary>
        [pbr::OriginalName("WITHOUT_DC_AND_NYQUIST")] WithoutDcAndNyquist = 1,
        /// <summary>
        /// The output dft tensor contains the nyquist component as the last
        /// two values.
        /// </summary>
        [pbr::OriginalName("WITH_NYQUIST")] WithNyquist = 2,
        /// <summary>
        /// The output dft tensor contains the dc component as the first two values
        /// and the nyquist component as the last two values.
        /// </summary>
        [pbr::OriginalName("WITH_DC_AND_NYQUIST")] WithDcAndNyquist = 3,
      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the AudioToTensorCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.AudioToTensorCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.AudioToTensorCalculatorOptions>(448635064, pb::FieldCodec.ForMessage(3589080514, global::Mediapipe.AudioToTensorCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
