// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/bert_preprocessor_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/bert_preprocessor_calculator.proto</summary>
  public static partial class BertPreprocessorCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/bert_preprocessor_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BertPreprocessorCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CmNQYWNrYWdlcy9jb20uZGF0ZWE4My5tZWRpYXBpcGVmb3Jkb3RzL1J1bnRp",
            "bWUvQ2FsY3VsYXRvcnMvdGVuc29yL2JlcnRfcHJlcHJvY2Vzc29yX2NhbGN1",
            "bGF0b3IucHJvdG8SCW1lZGlhcGlwZRpIUGFja2FnZXMvY29tLmRhdGVhODMu",
            "bWVkaWFwaXBlZm9yZG90cy9SdW50aW1lL0ZyYW1ld29yay9jYWxjdWxhdG9y",
            "LnByb3RvIr0BCiFCZXJ0UHJlcHJvY2Vzc29yQ2FsY3VsYXRvck9wdGlvbnMS",
            "GAoQYmVydF9tYXhfc2VxX2xlbhgBIAEoBRIhChloYXNfZHluYW1pY19pbnB1",
            "dF90ZW5zb3JzGAIgASgIMlsKA2V4dBIcLm1lZGlhcGlwZS5DYWxjdWxhdG9y",
            "T3B0aW9ucxjXqcXcASABKAsyLC5tZWRpYXBpcGUuQmVydFByZXByb2Nlc3Nv",
            "ckNhbGN1bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.BertPreprocessorCalculatorOptions), global::Mediapipe.BertPreprocessorCalculatorOptions.Parser, new[]{ "BertMaxSeqLen", "HasDynamicInputTensors" }, null, null, new pb::Extension[] { global::Mediapipe.BertPreprocessorCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BertPreprocessorCalculatorOptions : pb::IMessage<BertPreprocessorCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BertPreprocessorCalculatorOptions> _parser = new pb::MessageParser<BertPreprocessorCalculatorOptions>(() => new BertPreprocessorCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BertPreprocessorCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.BertPreprocessorCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BertPreprocessorCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BertPreprocessorCalculatorOptions(BertPreprocessorCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      bertMaxSeqLen_ = other.bertMaxSeqLen_;
      hasDynamicInputTensors_ = other.hasDynamicInputTensors_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BertPreprocessorCalculatorOptions Clone() {
      return new BertPreprocessorCalculatorOptions(this);
    }

    /// <summary>Field number for the "bert_max_seq_len" field.</summary>
    public const int BertMaxSeqLenFieldNumber = 1;
    private readonly static int BertMaxSeqLenDefaultValue = 0;

    private int bertMaxSeqLen_;
    /// <summary>
    /// The maximum input sequence length for the calculator's BERT model. Used
    /// if the model's input tensors have static shape.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BertMaxSeqLen {
      get { if ((_hasBits0 & 1) != 0) { return bertMaxSeqLen_; } else { return BertMaxSeqLenDefaultValue; } }
      set {
        _hasBits0 |= 1;
        bertMaxSeqLen_ = value;
      }
    }
    /// <summary>Gets whether the "bert_max_seq_len" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBertMaxSeqLen {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "bert_max_seq_len" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBertMaxSeqLen() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "has_dynamic_input_tensors" field.</summary>
    public const int HasDynamicInputTensorsFieldNumber = 2;
    private readonly static bool HasDynamicInputTensorsDefaultValue = false;

    private bool hasDynamicInputTensors_;
    /// <summary>
    /// Whether the BERT model's input tensors have dynamic shape.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDynamicInputTensors {
      get { if ((_hasBits0 & 2) != 0) { return hasDynamicInputTensors_; } else { return HasDynamicInputTensorsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        hasDynamicInputTensors_ = value;
      }
    }
    /// <summary>Gets whether the "has_dynamic_input_tensors" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHasDynamicInputTensors {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "has_dynamic_input_tensors" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHasDynamicInputTensors() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BertPreprocessorCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BertPreprocessorCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BertMaxSeqLen != other.BertMaxSeqLen) return false;
      if (HasDynamicInputTensors != other.HasDynamicInputTensors) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBertMaxSeqLen) hash ^= BertMaxSeqLen.GetHashCode();
      if (HasHasDynamicInputTensors) hash ^= HasDynamicInputTensors.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBertMaxSeqLen) {
        output.WriteRawTag(8);
        output.WriteInt32(BertMaxSeqLen);
      }
      if (HasHasDynamicInputTensors) {
        output.WriteRawTag(16);
        output.WriteBool(HasDynamicInputTensors);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBertMaxSeqLen) {
        output.WriteRawTag(8);
        output.WriteInt32(BertMaxSeqLen);
      }
      if (HasHasDynamicInputTensors) {
        output.WriteRawTag(16);
        output.WriteBool(HasDynamicInputTensors);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBertMaxSeqLen) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BertMaxSeqLen);
      }
      if (HasHasDynamicInputTensors) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BertPreprocessorCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasBertMaxSeqLen) {
        BertMaxSeqLen = other.BertMaxSeqLen;
      }
      if (other.HasHasDynamicInputTensors) {
        HasDynamicInputTensors = other.HasDynamicInputTensors;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BertMaxSeqLen = input.ReadInt32();
            break;
          }
          case 16: {
            HasDynamicInputTensors = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BertMaxSeqLen = input.ReadInt32();
            break;
          }
          case 16: {
            HasDynamicInputTensors = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the BertPreprocessorCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.BertPreprocessorCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.BertPreprocessorCalculatorOptions>(462509271, pb::FieldCodec.ForMessage(3700074170, global::Mediapipe.BertPreprocessorCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
