// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/feedback_tensors_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/feedback_tensors_calculator.proto</summary>
  public static partial class FeedbackTensorsCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/feedback_tensors_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FeedbackTensorsCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CmJQYWNrYWdlcy9jb20uZGF0ZWE4My5tZWRpYXBpcGVmb3Jkb3RzL1J1bnRp",
            "bWUvQ2FsY3VsYXRvcnMvdGVuc29yL2ZlZWRiYWNrX3RlbnNvcnNfY2FsY3Vs",
            "YXRvci5wcm90bxIJbWVkaWFwaXBlGkhQYWNrYWdlcy9jb20uZGF0ZWE4My5t",
            "ZWRpYXBpcGVmb3Jkb3RzL1J1bnRpbWUvRnJhbWV3b3JrL2NhbGN1bGF0b3Iu",
            "cHJvdG8iuwMKIEZlZWRiYWNrVGVuc29yc0NhbGN1bGF0b3JPcHRpb25zElYK",
            "FWZlZWRiYWNrX3RlbnNvcl9zaGFwZRgBIAEoCzI3Lm1lZGlhcGlwZS5GZWVk",
            "YmFja1RlbnNvcnNDYWxjdWxhdG9yT3B0aW9ucy5UZW5zb3JTaGFwZRIfChRu",
            "dW1fZmVlZGJhY2tfdGVuc29ycxgCIAEoBToBMRJfCghsb2NhdGlvbhgDIAEo",
            "DjJDLm1lZGlhcGlwZS5GZWVkYmFja1RlbnNvcnNDYWxjdWxhdG9yT3B0aW9u",
            "cy5GZWVkYmFja1RlbnNvcnNMb2NhdGlvbjoIQVBQRU5ERUQaHwoLVGVuc29y",
            "U2hhcGUSEAoEZGltcxgBIAMoBUICEAEiQAoXRmVlZGJhY2tUZW5zb3JzTG9j",
            "YXRpb24SCAoETk9ORRAAEg0KCVBSRVBFTkRFRBABEgwKCEFQUEVOREVEEAIy",
            "WgoDZXh0EhwubWVkaWFwaXBlLkNhbGN1bGF0b3JPcHRpb25zGPz5oOIBIAEo",
            "CzIrLm1lZGlhcGlwZS5GZWVkYmFja1RlbnNvcnNDYWxjdWxhdG9yT3B0aW9u",
            "cw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FeedbackTensorsCalculatorOptions), global::Mediapipe.FeedbackTensorsCalculatorOptions.Parser, new[]{ "FeedbackTensorShape", "NumFeedbackTensors", "Location" }, null, new[]{ typeof(global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation) }, new pb::Extension[] { global::Mediapipe.FeedbackTensorsCalculatorOptions.Extensions.Ext }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape), global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape.Parser, new[]{ "Dims" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FeedbackTensorsCalculatorOptions : pb::IMessage<FeedbackTensorsCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FeedbackTensorsCalculatorOptions> _parser = new pb::MessageParser<FeedbackTensorsCalculatorOptions>(() => new FeedbackTensorsCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FeedbackTensorsCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.FeedbackTensorsCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackTensorsCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackTensorsCalculatorOptions(FeedbackTensorsCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      feedbackTensorShape_ = other.feedbackTensorShape_ != null ? other.feedbackTensorShape_.Clone() : null;
      numFeedbackTensors_ = other.numFeedbackTensors_;
      location_ = other.location_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackTensorsCalculatorOptions Clone() {
      return new FeedbackTensorsCalculatorOptions(this);
    }

    /// <summary>Field number for the "feedback_tensor_shape" field.</summary>
    public const int FeedbackTensorShapeFieldNumber = 1;
    private global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape feedbackTensorShape_;
    /// <summary>
    /// The shape of the feedback tensors to add.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape FeedbackTensorShape {
      get { return feedbackTensorShape_; }
      set {
        feedbackTensorShape_ = value;
      }
    }

    /// <summary>Field number for the "num_feedback_tensors" field.</summary>
    public const int NumFeedbackTensorsFieldNumber = 2;
    private readonly static int NumFeedbackTensorsDefaultValue = 1;

    private int numFeedbackTensors_;
    /// <summary>
    /// The number of the feedback tensors to add.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumFeedbackTensors {
      get { if ((_hasBits0 & 1) != 0) { return numFeedbackTensors_; } else { return NumFeedbackTensorsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        numFeedbackTensors_ = value;
      }
    }
    /// <summary>Gets whether the "num_feedback_tensors" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumFeedbackTensors {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "num_feedback_tensors" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumFeedbackTensors() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 3;
    private readonly static global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation LocationDefaultValue = global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation.Appended;

    private global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation location_;
    /// <summary>
    /// Determines the location of the feedback tensor(s) in the output vector.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation Location {
      get { if ((_hasBits0 & 2) != 0) { return location_; } else { return LocationDefaultValue; } }
      set {
        _hasBits0 |= 2;
        location_ = value;
      }
    }
    /// <summary>Gets whether the "location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLocation {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLocation() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FeedbackTensorsCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FeedbackTensorsCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FeedbackTensorShape, other.FeedbackTensorShape)) return false;
      if (NumFeedbackTensors != other.NumFeedbackTensors) return false;
      if (Location != other.Location) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (feedbackTensorShape_ != null) hash ^= FeedbackTensorShape.GetHashCode();
      if (HasNumFeedbackTensors) hash ^= NumFeedbackTensors.GetHashCode();
      if (HasLocation) hash ^= Location.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (feedbackTensorShape_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FeedbackTensorShape);
      }
      if (HasNumFeedbackTensors) {
        output.WriteRawTag(16);
        output.WriteInt32(NumFeedbackTensors);
      }
      if (HasLocation) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Location);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (feedbackTensorShape_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FeedbackTensorShape);
      }
      if (HasNumFeedbackTensors) {
        output.WriteRawTag(16);
        output.WriteInt32(NumFeedbackTensors);
      }
      if (HasLocation) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Location);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (feedbackTensorShape_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FeedbackTensorShape);
      }
      if (HasNumFeedbackTensors) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumFeedbackTensors);
      }
      if (HasLocation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Location);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FeedbackTensorsCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.feedbackTensorShape_ != null) {
        if (feedbackTensorShape_ == null) {
          FeedbackTensorShape = new global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape();
        }
        FeedbackTensorShape.MergeFrom(other.FeedbackTensorShape);
      }
      if (other.HasNumFeedbackTensors) {
        NumFeedbackTensors = other.NumFeedbackTensors;
      }
      if (other.HasLocation) {
        Location = other.Location;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (feedbackTensorShape_ == null) {
              FeedbackTensorShape = new global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape();
            }
            input.ReadMessage(FeedbackTensorShape);
            break;
          }
          case 16: {
            NumFeedbackTensors = input.ReadInt32();
            break;
          }
          case 24: {
            Location = (global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (feedbackTensorShape_ == null) {
              FeedbackTensorShape = new global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.TensorShape();
            }
            input.ReadMessage(FeedbackTensorShape);
            break;
          }
          case 16: {
            NumFeedbackTensors = input.ReadInt32();
            break;
          }
          case 24: {
            Location = (global::Mediapipe.FeedbackTensorsCalculatorOptions.Types.FeedbackTensorsLocation) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FeedbackTensorsCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum FeedbackTensorsLocation {
        /// <summary>
        /// The feedback tensors will not be added.
        /// </summary>
        [pbr::OriginalName("NONE")] None = 0,
        /// <summary>
        /// The feedback tensors will be added before the input tensors.
        /// </summary>
        [pbr::OriginalName("PREPENDED")] Prepended = 1,
        /// <summary>
        /// The feedback tensors will be added after the input tensors.
        /// </summary>
        [pbr::OriginalName("APPENDED")] Appended = 2,
      }

      /// <summary>
      /// Represents the dimensions of a tensor starting from the outermost size.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class TensorShape : pb::IMessage<TensorShape>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TensorShape> _parser = new pb::MessageParser<TensorShape>(() => new TensorShape());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TensorShape> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mediapipe.FeedbackTensorsCalculatorOptions.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TensorShape() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TensorShape(TensorShape other) : this() {
          dims_ = other.dims_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TensorShape Clone() {
          return new TensorShape(this);
        }

        /// <summary>Field number for the "dims" field.</summary>
        public const int DimsFieldNumber = 1;
        private static readonly pb::FieldCodec<int> _repeated_dims_codec
            = pb::FieldCodec.ForInt32(10);
        private readonly pbc::RepeatedField<int> dims_ = new pbc::RepeatedField<int>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<int> Dims {
          get { return dims_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TensorShape);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TensorShape other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!dims_.Equals(other.dims_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= dims_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          dims_.WriteTo(output, _repeated_dims_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          dims_.WriteTo(ref output, _repeated_dims_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += dims_.CalculateSize(_repeated_dims_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TensorShape other) {
          if (other == null) {
            return;
          }
          dims_.Add(other.dims_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10:
              case 8: {
                dims_.AddEntriesFrom(input, _repeated_dims_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10:
              case 8: {
                dims_.AddEntriesFrom(ref input, _repeated_dims_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the FeedbackTensorsCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FeedbackTensorsCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FeedbackTensorsCalculatorOptions>(474496252, pb::FieldCodec.ForMessage(3795970018, global::Mediapipe.FeedbackTensorsCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
