// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/tensors_to_audio_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/tensors_to_audio_calculator.proto</summary>
  public static partial class TensorsToAudioCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Packages/com.datea83.mediapipefordots/Runtime/Calculators/tensor/tensors_to_audio_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TensorsToAudioCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CmJQYWNrYWdlcy9jb20uZGF0ZWE4My5tZWRpYXBpcGVmb3Jkb3RzL1J1bnRp",
            "bWUvQ2FsY3VsYXRvcnMvdGVuc29yL3RlbnNvcnNfdG9fYXVkaW9fY2FsY3Vs",
            "YXRvci5wcm90bxIJbWVkaWFwaXBlGkhQYWNrYWdlcy9jb20uZGF0ZWE4My5t",
            "ZWRpYXBpcGVmb3Jkb3RzL1J1bnRpbWUvRnJhbWV3b3JrL2NhbGN1bGF0b3Iu",
            "cHJvdG8ivQMKH1RlbnNvcnNUb0F1ZGlvQ2FsY3VsYXRvck9wdGlvbnMSEAoI",
            "ZmZ0X3NpemUYASABKAMSEwoLbnVtX3NhbXBsZXMYAiABKAMSIgoXbnVtX292",
            "ZXJsYXBwaW5nX3NhbXBsZXMYAyABKAM6ATASYwoRZGZ0X3RlbnNvcl9mb3Jt",
            "YXQYCyABKA4yOi5tZWRpYXBpcGUuVGVuc29yc1RvQXVkaW9DYWxjdWxhdG9y",
            "T3B0aW9ucy5EZnRUZW5zb3JGb3JtYXQ6DFdJVEhfTllRVUlTVBIWCg52b2x1",
            "bWVfZ2Fpbl9kYhgMIAEoASJ3Cg9EZnRUZW5zb3JGb3JtYXQSHQoZREZUX1RF",
            "TlNPUl9GT1JNQVRfVU5LTk9XThAAEhoKFldJVEhPVVRfRENfQU5EX05ZUVVJ",
            "U1QQARIQCgxXSVRIX05ZUVVJU1QQAhIXChNXSVRIX0RDX0FORF9OWVFVSVNU",
            "EAMyWQoDZXh0EhwubWVkaWFwaXBlLkNhbGN1bGF0b3JPcHRpb25zGLCT9+YB",
            "IAEoCzIqLm1lZGlhcGlwZS5UZW5zb3JzVG9BdWRpb0NhbGN1bGF0b3JPcHRp",
            "b25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.TensorsToAudioCalculatorOptions), global::Mediapipe.TensorsToAudioCalculatorOptions.Parser, new[]{ "FftSize", "NumSamples", "NumOverlappingSamples", "DftTensorFormat", "VolumeGainDb" }, null, new[]{ typeof(global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat) }, new pb::Extension[] { global::Mediapipe.TensorsToAudioCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TensorsToAudioCalculatorOptions : pb::IMessage<TensorsToAudioCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TensorsToAudioCalculatorOptions> _parser = new pb::MessageParser<TensorsToAudioCalculatorOptions>(() => new TensorsToAudioCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TensorsToAudioCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.TensorsToAudioCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToAudioCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToAudioCalculatorOptions(TensorsToAudioCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      fftSize_ = other.fftSize_;
      numSamples_ = other.numSamples_;
      numOverlappingSamples_ = other.numOverlappingSamples_;
      dftTensorFormat_ = other.dftTensorFormat_;
      volumeGainDb_ = other.volumeGainDb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToAudioCalculatorOptions Clone() {
      return new TensorsToAudioCalculatorOptions(this);
    }

    /// <summary>Field number for the "fft_size" field.</summary>
    public const int FftSizeFieldNumber = 1;
    private readonly static long FftSizeDefaultValue = 0L;

    private long fftSize_;
    /// <summary>
    /// Size of the fft in number of bins. If set, the calculator will do ifft
    /// on the input tensor.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FftSize {
      get { if ((_hasBits0 & 1) != 0) { return fftSize_; } else { return FftSizeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        fftSize_ = value;
      }
    }
    /// <summary>Gets whether the "fft_size" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFftSize {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "fft_size" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFftSize() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "num_samples" field.</summary>
    public const int NumSamplesFieldNumber = 2;
    private readonly static long NumSamplesDefaultValue = 0L;

    private long numSamples_;
    /// <summary>
    /// The number of samples per channel the output audio has.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NumSamples {
      get { if ((_hasBits0 & 2) != 0) { return numSamples_; } else { return NumSamplesDefaultValue; } }
      set {
        _hasBits0 |= 2;
        numSamples_ = value;
      }
    }
    /// <summary>Gets whether the "num_samples" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumSamples {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "num_samples" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumSamples() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "num_overlapping_samples" field.</summary>
    public const int NumOverlappingSamplesFieldNumber = 3;
    private readonly static long NumOverlappingSamplesDefaultValue = 0L;

    private long numOverlappingSamples_;
    /// <summary>
    /// The number of overlapping samples between adjacent windows.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NumOverlappingSamples {
      get { if ((_hasBits0 & 4) != 0) { return numOverlappingSamples_; } else { return NumOverlappingSamplesDefaultValue; } }
      set {
        _hasBits0 |= 4;
        numOverlappingSamples_ = value;
      }
    }
    /// <summary>Gets whether the "num_overlapping_samples" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumOverlappingSamples {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "num_overlapping_samples" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumOverlappingSamples() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "dft_tensor_format" field.</summary>
    public const int DftTensorFormatFieldNumber = 11;
    private readonly static global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat DftTensorFormatDefaultValue = global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat.WithNyquist;

    private global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat dftTensorFormat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat DftTensorFormat {
      get { if ((_hasBits0 & 8) != 0) { return dftTensorFormat_; } else { return DftTensorFormatDefaultValue; } }
      set {
        _hasBits0 |= 8;
        dftTensorFormat_ = value;
      }
    }
    /// <summary>Gets whether the "dft_tensor_format" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDftTensorFormat {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "dft_tensor_format" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDftTensorFormat() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "volume_gain_db" field.</summary>
    public const int VolumeGainDbFieldNumber = 12;
    private readonly static double VolumeGainDbDefaultValue = 0D;

    private double volumeGainDb_;
    /// <summary>
    /// The volume gain, measured in dB.
    /// Scale the output audio amplitude by 10^(volume_gain_db/20).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double VolumeGainDb {
      get { if ((_hasBits0 & 16) != 0) { return volumeGainDb_; } else { return VolumeGainDbDefaultValue; } }
      set {
        _hasBits0 |= 16;
        volumeGainDb_ = value;
      }
    }
    /// <summary>Gets whether the "volume_gain_db" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolumeGainDb {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "volume_gain_db" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolumeGainDb() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TensorsToAudioCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TensorsToAudioCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FftSize != other.FftSize) return false;
      if (NumSamples != other.NumSamples) return false;
      if (NumOverlappingSamples != other.NumOverlappingSamples) return false;
      if (DftTensorFormat != other.DftTensorFormat) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(VolumeGainDb, other.VolumeGainDb)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasFftSize) hash ^= FftSize.GetHashCode();
      if (HasNumSamples) hash ^= NumSamples.GetHashCode();
      if (HasNumOverlappingSamples) hash ^= NumOverlappingSamples.GetHashCode();
      if (HasDftTensorFormat) hash ^= DftTensorFormat.GetHashCode();
      if (HasVolumeGainDb) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(VolumeGainDb);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasFftSize) {
        output.WriteRawTag(8);
        output.WriteInt64(FftSize);
      }
      if (HasNumSamples) {
        output.WriteRawTag(16);
        output.WriteInt64(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        output.WriteRawTag(24);
        output.WriteInt64(NumOverlappingSamples);
      }
      if (HasDftTensorFormat) {
        output.WriteRawTag(88);
        output.WriteEnum((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        output.WriteRawTag(97);
        output.WriteDouble(VolumeGainDb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasFftSize) {
        output.WriteRawTag(8);
        output.WriteInt64(FftSize);
      }
      if (HasNumSamples) {
        output.WriteRawTag(16);
        output.WriteInt64(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        output.WriteRawTag(24);
        output.WriteInt64(NumOverlappingSamples);
      }
      if (HasDftTensorFormat) {
        output.WriteRawTag(88);
        output.WriteEnum((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        output.WriteRawTag(97);
        output.WriteDouble(VolumeGainDb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasFftSize) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FftSize);
      }
      if (HasNumSamples) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumSamples);
      }
      if (HasNumOverlappingSamples) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumOverlappingSamples);
      }
      if (HasDftTensorFormat) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DftTensorFormat);
      }
      if (HasVolumeGainDb) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TensorsToAudioCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasFftSize) {
        FftSize = other.FftSize;
      }
      if (other.HasNumSamples) {
        NumSamples = other.NumSamples;
      }
      if (other.HasNumOverlappingSamples) {
        NumOverlappingSamples = other.NumOverlappingSamples;
      }
      if (other.HasDftTensorFormat) {
        DftTensorFormat = other.DftTensorFormat;
      }
      if (other.HasVolumeGainDb) {
        VolumeGainDb = other.VolumeGainDb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FftSize = input.ReadInt64();
            break;
          }
          case 16: {
            NumSamples = input.ReadInt64();
            break;
          }
          case 24: {
            NumOverlappingSamples = input.ReadInt64();
            break;
          }
          case 88: {
            DftTensorFormat = (global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat) input.ReadEnum();
            break;
          }
          case 97: {
            VolumeGainDb = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FftSize = input.ReadInt64();
            break;
          }
          case 16: {
            NumSamples = input.ReadInt64();
            break;
          }
          case 24: {
            NumOverlappingSamples = input.ReadInt64();
            break;
          }
          case 88: {
            DftTensorFormat = (global::Mediapipe.TensorsToAudioCalculatorOptions.Types.DftTensorFormat) input.ReadEnum();
            break;
          }
          case 97: {
            VolumeGainDb = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TensorsToAudioCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum DftTensorFormat {
        [pbr::OriginalName("DFT_TENSOR_FORMAT_UNKNOWN")] Unknown = 0,
        /// <summary>
        /// The input dft tensor without dc and nyquist components.
        /// </summary>
        [pbr::OriginalName("WITHOUT_DC_AND_NYQUIST")] WithoutDcAndNyquist = 1,
        /// <summary>
        /// The input dft tensor contains the nyquist component as the last
        /// two values.
        /// </summary>
        [pbr::OriginalName("WITH_NYQUIST")] WithNyquist = 2,
        /// <summary>
        /// The input dft tensor contains the dc component as the first two values
        /// and the nyquist component as the last two values.
        /// </summary>
        [pbr::OriginalName("WITH_DC_AND_NYQUIST")] WithDcAndNyquist = 3,
      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the TensorsToAudioCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.TensorsToAudioCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.TensorsToAudioCalculatorOptions>(484297136, pb::FieldCodec.ForMessage(3874377090, global::Mediapipe.TensorsToAudioCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
