// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bypass_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from bypass_calculator.proto</summary>
  public static partial class BypassCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for bypass_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BypassCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdieXBhc3NfY2FsY3VsYXRvci5wcm90bxIJbWVkaWFwaXBlGhBjYWxjdWxh",
            "dG9yLnByb3RvIqMBChdCeXBhc3NDYWxjdWxhdG9yT3B0aW9ucxIZChFwYXNz",
            "X2lucHV0X3N0cmVhbRgBIAMoCRIaChJwYXNzX291dHB1dF9zdHJlYW0YAiAD",
            "KAkyUQoDZXh0EhwubWVkaWFwaXBlLkNhbGN1bGF0b3JPcHRpb25zGJ3hveUB",
            "IAEoCzIiLm1lZGlhcGlwZS5CeXBhc3NDYWxjdWxhdG9yT3B0aW9ucw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.BypassCalculatorOptions), global::Mediapipe.BypassCalculatorOptions.Parser, new[]{ "PassInputStream", "PassOutputStream" }, null, null, new pb::Extension[] { global::Mediapipe.BypassCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BypassCalculatorOptions : pb::IMessage<BypassCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BypassCalculatorOptions> _parser = new pb::MessageParser<BypassCalculatorOptions>(() => new BypassCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BypassCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.BypassCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BypassCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BypassCalculatorOptions(BypassCalculatorOptions other) : this() {
      passInputStream_ = other.passInputStream_.Clone();
      passOutputStream_ = other.passOutputStream_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BypassCalculatorOptions Clone() {
      return new BypassCalculatorOptions(this);
    }

    /// <summary>Field number for the "pass_input_stream" field.</summary>
    public const int PassInputStreamFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_passInputStream_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> passInputStream_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Names an input stream or streams to pass through, by "TAG:index".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PassInputStream {
      get { return passInputStream_; }
    }

    /// <summary>Field number for the "pass_output_stream" field.</summary>
    public const int PassOutputStreamFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_passOutputStream_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> passOutputStream_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Names an output stream or streams to pass through, by "TAG:index".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PassOutputStream {
      get { return passOutputStream_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BypassCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BypassCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!passInputStream_.Equals(other.passInputStream_)) return false;
      if(!passOutputStream_.Equals(other.passOutputStream_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= passInputStream_.GetHashCode();
      hash ^= passOutputStream_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      passInputStream_.WriteTo(output, _repeated_passInputStream_codec);
      passOutputStream_.WriteTo(output, _repeated_passOutputStream_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      passInputStream_.WriteTo(ref output, _repeated_passInputStream_codec);
      passOutputStream_.WriteTo(ref output, _repeated_passOutputStream_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += passInputStream_.CalculateSize(_repeated_passInputStream_codec);
      size += passOutputStream_.CalculateSize(_repeated_passOutputStream_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BypassCalculatorOptions other) {
      if (other == null) {
        return;
      }
      passInputStream_.Add(other.passInputStream_);
      passOutputStream_.Add(other.passOutputStream_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            passInputStream_.AddEntriesFrom(input, _repeated_passInputStream_codec);
            break;
          }
          case 18: {
            passOutputStream_.AddEntriesFrom(input, _repeated_passOutputStream_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            passInputStream_.AddEntriesFrom(ref input, _repeated_passInputStream_codec);
            break;
          }
          case 18: {
            passOutputStream_.AddEntriesFrom(ref input, _repeated_passOutputStream_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the BypassCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.BypassCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.BypassCalculatorOptions>(481259677, pb::FieldCodec.ForMessage(3850077418, global::Mediapipe.BypassCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
