// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: get_vector_item_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from get_vector_item_calculator.proto</summary>
  public static partial class GetVectorItemCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for get_vector_item_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetVectorItemCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBnZXRfdmVjdG9yX2l0ZW1fY2FsY3VsYXRvci5wcm90bxIJbWVkaWFwaXBl",
            "GhBjYWxjdWxhdG9yLnByb3RvIqsBCh5HZXRWZWN0b3JJdGVtQ2FsY3VsYXRv",
            "ck9wdGlvbnMSEgoKaXRlbV9pbmRleBgBIAEoBRIbChNvdXRwdXRfZW1wdHlf",
            "b25fb29iGAIgASgIMlgKA2V4dBIcLm1lZGlhcGlwZS5DYWxjdWxhdG9yT3B0",
            "aW9ucxjvkoTdASABKAsyKS5tZWRpYXBpcGUuR2V0VmVjdG9ySXRlbUNhbGN1",
            "bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.GetVectorItemCalculatorOptions), global::Mediapipe.GetVectorItemCalculatorOptions.Parser, new[]{ "ItemIndex", "OutputEmptyOnOob" }, null, null, new pb::Extension[] { global::Mediapipe.GetVectorItemCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetVectorItemCalculatorOptions : pb::IMessage<GetVectorItemCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetVectorItemCalculatorOptions> _parser = new pb::MessageParser<GetVectorItemCalculatorOptions>(() => new GetVectorItemCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetVectorItemCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GetVectorItemCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetVectorItemCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetVectorItemCalculatorOptions(GetVectorItemCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      itemIndex_ = other.itemIndex_;
      outputEmptyOnOob_ = other.outputEmptyOnOob_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetVectorItemCalculatorOptions Clone() {
      return new GetVectorItemCalculatorOptions(this);
    }

    /// <summary>Field number for the "item_index" field.</summary>
    public const int ItemIndexFieldNumber = 1;
    private readonly static int ItemIndexDefaultValue = 0;

    private int itemIndex_;
    /// <summary>
    /// Index of vector item to get. INDEX input stream can be used instead, or to
    /// override.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemIndex {
      get { if ((_hasBits0 & 1) != 0) { return itemIndex_; } else { return ItemIndexDefaultValue; } }
      set {
        _hasBits0 |= 1;
        itemIndex_ = value;
      }
    }
    /// <summary>Gets whether the "item_index" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemIndex {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "item_index" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemIndex() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "output_empty_on_oob" field.</summary>
    public const int OutputEmptyOnOobFieldNumber = 2;
    private readonly static bool OutputEmptyOnOobDefaultValue = false;

    private bool outputEmptyOnOob_;
    /// <summary>
    /// Set to true to output an empty packet when the index is out of bounds.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OutputEmptyOnOob {
      get { if ((_hasBits0 & 2) != 0) { return outputEmptyOnOob_; } else { return OutputEmptyOnOobDefaultValue; } }
      set {
        _hasBits0 |= 2;
        outputEmptyOnOob_ = value;
      }
    }
    /// <summary>Gets whether the "output_empty_on_oob" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOutputEmptyOnOob {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "output_empty_on_oob" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOutputEmptyOnOob() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetVectorItemCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetVectorItemCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemIndex != other.ItemIndex) return false;
      if (OutputEmptyOnOob != other.OutputEmptyOnOob) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasItemIndex) hash ^= ItemIndex.GetHashCode();
      if (HasOutputEmptyOnOob) hash ^= OutputEmptyOnOob.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasItemIndex) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemIndex);
      }
      if (HasOutputEmptyOnOob) {
        output.WriteRawTag(16);
        output.WriteBool(OutputEmptyOnOob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasItemIndex) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemIndex);
      }
      if (HasOutputEmptyOnOob) {
        output.WriteRawTag(16);
        output.WriteBool(OutputEmptyOnOob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasItemIndex) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemIndex);
      }
      if (HasOutputEmptyOnOob) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetVectorItemCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasItemIndex) {
        ItemIndex = other.ItemIndex;
      }
      if (other.HasOutputEmptyOnOob) {
        OutputEmptyOnOob = other.OutputEmptyOnOob;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemIndex = input.ReadInt32();
            break;
          }
          case 16: {
            OutputEmptyOnOob = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemIndex = input.ReadInt32();
            break;
          }
          case 16: {
            OutputEmptyOnOob = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the GetVectorItemCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.GetVectorItemCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.GetVectorItemCalculatorOptions>(463538543, pb::FieldCodec.ForMessage(3708308346, global::Mediapipe.GetVectorItemCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
