// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: graph_runtime_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from graph_runtime_info.proto</summary>
  public static partial class GraphRuntimeInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for graph_runtime_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GraphRuntimeInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhncmFwaF9ydW50aW1lX2luZm8ucHJvdG8SCW1lZGlhcGlwZSKGAQoWSW5w",
            "dXRTdHJlYW1SdW50aW1lSW5mbxITCgtzdHJlYW1fbmFtZRgBIAEoCRISCgpx",
            "dWV1ZV9zaXplGAIgASgFEh8KF251bWJlcl9vZl9wYWNrZXRzX2FkZGVkGAMg",
            "ASgFEiIKGm1pbmltdW1fdGltZXN0YW1wX29yX2JvdW5kGAQgASgDInMKF091",
            "dHB1dFN0cmVhbVJ1bnRpbWVJbmZvEhMKC3N0cmVhbV9uYW1lGAEgASgJEh8K",
            "F251bWJlcl9vZl9wYWNrZXRzX2FkZGVkGAIgASgFEiIKGm1pbmltdW1fdGlt",
            "ZXN0YW1wX29yX2JvdW5kGAMgASgDIpICChVDYWxjdWxhdG9yUnVudGltZUlu",
            "Zm8SFwoPY2FsY3VsYXRvcl9uYW1lGAEgASgJEiIKGmxhc3RfcHJvY2Vzc19z",
            "dGFydF91bml4X3VzGAIgASgDEiMKG2xhc3RfcHJvY2Vzc19maW5pc2hfdW5p",
            "eF91cxgDIAEoAxIXCg90aW1lc3RhbXBfYm91bmQYBCABKAMSPQoSaW5wdXRf",
            "c3RyZWFtX2luZm9zGAUgAygLMiEubWVkaWFwaXBlLklucHV0U3RyZWFtUnVu",
            "dGltZUluZm8SPwoTb3V0cHV0X3N0cmVhbV9pbmZvcxgGIAMoCzIiLm1lZGlh",
            "cGlwZS5PdXRwdXRTdHJlYW1SdW50aW1lSW5mbyJsChBHcmFwaFJ1bnRpbWVJ",
            "bmZvEhwKFGNhcHR1cmVfdGltZV91bml4X3VzGAEgASgDEjoKEGNhbGN1bGF0",
            "b3JfaW5mb3MYAiADKAsyIC5tZWRpYXBpcGUuQ2FsY3VsYXRvclJ1bnRpbWVJ",
            "bmZvQjMKGmNvbS5nb29nbGUubWVkaWFwaXBlLnByb3RvQhVHcmFwaFJ1bnRp",
            "bWVJbmZvUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.InputStreamRuntimeInfo), global::Mediapipe.InputStreamRuntimeInfo.Parser, new[]{ "StreamName", "QueueSize", "NumberOfPacketsAdded", "MinimumTimestampOrBound" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.OutputStreamRuntimeInfo), global::Mediapipe.OutputStreamRuntimeInfo.Parser, new[]{ "StreamName", "NumberOfPacketsAdded", "MinimumTimestampOrBound" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.CalculatorRuntimeInfo), global::Mediapipe.CalculatorRuntimeInfo.Parser, new[]{ "CalculatorName", "LastProcessStartUnixUs", "LastProcessFinishUnixUs", "TimestampBound", "InputStreamInfos", "OutputStreamInfos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.GraphRuntimeInfo), global::Mediapipe.GraphRuntimeInfo.Parser, new[]{ "CaptureTimeUnixUs", "CalculatorInfos" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The runtime info for an input stream.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InputStreamRuntimeInfo : pb::IMessage<InputStreamRuntimeInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InputStreamRuntimeInfo> _parser = new pb::MessageParser<InputStreamRuntimeInfo>(() => new InputStreamRuntimeInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InputStreamRuntimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GraphRuntimeInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputStreamRuntimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputStreamRuntimeInfo(InputStreamRuntimeInfo other) : this() {
      streamName_ = other.streamName_;
      queueSize_ = other.queueSize_;
      numberOfPacketsAdded_ = other.numberOfPacketsAdded_;
      minimumTimestampOrBound_ = other.minimumTimestampOrBound_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputStreamRuntimeInfo Clone() {
      return new InputStreamRuntimeInfo(this);
    }

    /// <summary>Field number for the "stream_name" field.</summary>
    public const int StreamNameFieldNumber = 1;
    private string streamName_ = "";
    /// <summary>
    /// The name of the stream in the format "TAG:index:stream_name"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StreamName {
      get { return streamName_; }
      set {
        streamName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "queue_size" field.</summary>
    public const int QueueSizeFieldNumber = 2;
    private int queueSize_;
    /// <summary>
    /// The number of packets in the queue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QueueSize {
      get { return queueSize_; }
      set {
        queueSize_ = value;
      }
    }

    /// <summary>Field number for the "number_of_packets_added" field.</summary>
    public const int NumberOfPacketsAddedFieldNumber = 3;
    private int numberOfPacketsAdded_;
    /// <summary>
    /// The total number of packets added to the queue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfPacketsAdded {
      get { return numberOfPacketsAdded_; }
      set {
        numberOfPacketsAdded_ = value;
      }
    }

    /// <summary>Field number for the "minimum_timestamp_or_bound" field.</summary>
    public const int MinimumTimestampOrBoundFieldNumber = 4;
    private long minimumTimestampOrBound_;
    /// <summary>
    /// The minimum timestamp or timestanp bound of the stream.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MinimumTimestampOrBound {
      get { return minimumTimestampOrBound_; }
      set {
        minimumTimestampOrBound_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InputStreamRuntimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InputStreamRuntimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StreamName != other.StreamName) return false;
      if (QueueSize != other.QueueSize) return false;
      if (NumberOfPacketsAdded != other.NumberOfPacketsAdded) return false;
      if (MinimumTimestampOrBound != other.MinimumTimestampOrBound) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StreamName.Length != 0) hash ^= StreamName.GetHashCode();
      if (QueueSize != 0) hash ^= QueueSize.GetHashCode();
      if (NumberOfPacketsAdded != 0) hash ^= NumberOfPacketsAdded.GetHashCode();
      if (MinimumTimestampOrBound != 0L) hash ^= MinimumTimestampOrBound.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StreamName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StreamName);
      }
      if (QueueSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QueueSize);
      }
      if (NumberOfPacketsAdded != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StreamName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StreamName);
      }
      if (QueueSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QueueSize);
      }
      if (NumberOfPacketsAdded != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StreamName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StreamName);
      }
      if (QueueSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QueueSize);
      }
      if (NumberOfPacketsAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InputStreamRuntimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.StreamName.Length != 0) {
        StreamName = other.StreamName;
      }
      if (other.QueueSize != 0) {
        QueueSize = other.QueueSize;
      }
      if (other.NumberOfPacketsAdded != 0) {
        NumberOfPacketsAdded = other.NumberOfPacketsAdded;
      }
      if (other.MinimumTimestampOrBound != 0L) {
        MinimumTimestampOrBound = other.MinimumTimestampOrBound;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StreamName = input.ReadString();
            break;
          }
          case 16: {
            QueueSize = input.ReadInt32();
            break;
          }
          case 24: {
            NumberOfPacketsAdded = input.ReadInt32();
            break;
          }
          case 32: {
            MinimumTimestampOrBound = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StreamName = input.ReadString();
            break;
          }
          case 16: {
            QueueSize = input.ReadInt32();
            break;
          }
          case 24: {
            NumberOfPacketsAdded = input.ReadInt32();
            break;
          }
          case 32: {
            MinimumTimestampOrBound = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The runtime info for an output stream.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OutputStreamRuntimeInfo : pb::IMessage<OutputStreamRuntimeInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OutputStreamRuntimeInfo> _parser = new pb::MessageParser<OutputStreamRuntimeInfo>(() => new OutputStreamRuntimeInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OutputStreamRuntimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GraphRuntimeInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputStreamRuntimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputStreamRuntimeInfo(OutputStreamRuntimeInfo other) : this() {
      streamName_ = other.streamName_;
      numberOfPacketsAdded_ = other.numberOfPacketsAdded_;
      minimumTimestampOrBound_ = other.minimumTimestampOrBound_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputStreamRuntimeInfo Clone() {
      return new OutputStreamRuntimeInfo(this);
    }

    /// <summary>Field number for the "stream_name" field.</summary>
    public const int StreamNameFieldNumber = 1;
    private string streamName_ = "";
    /// <summary>
    /// The name of the stream in the format "TAG:index:stream_name"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StreamName {
      get { return streamName_; }
      set {
        streamName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "number_of_packets_added" field.</summary>
    public const int NumberOfPacketsAddedFieldNumber = 2;
    private int numberOfPacketsAdded_;
    /// <summary>
    /// The total number of packets added to the queue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfPacketsAdded {
      get { return numberOfPacketsAdded_; }
      set {
        numberOfPacketsAdded_ = value;
      }
    }

    /// <summary>Field number for the "minimum_timestamp_or_bound" field.</summary>
    public const int MinimumTimestampOrBoundFieldNumber = 3;
    private long minimumTimestampOrBound_;
    /// <summary>
    /// The minimum timestamp or timestanp bound of the stream.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MinimumTimestampOrBound {
      get { return minimumTimestampOrBound_; }
      set {
        minimumTimestampOrBound_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OutputStreamRuntimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OutputStreamRuntimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StreamName != other.StreamName) return false;
      if (NumberOfPacketsAdded != other.NumberOfPacketsAdded) return false;
      if (MinimumTimestampOrBound != other.MinimumTimestampOrBound) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StreamName.Length != 0) hash ^= StreamName.GetHashCode();
      if (NumberOfPacketsAdded != 0) hash ^= NumberOfPacketsAdded.GetHashCode();
      if (MinimumTimestampOrBound != 0L) hash ^= MinimumTimestampOrBound.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StreamName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StreamName);
      }
      if (NumberOfPacketsAdded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StreamName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StreamName);
      }
      if (NumberOfPacketsAdded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StreamName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StreamName);
      }
      if (NumberOfPacketsAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfPacketsAdded);
      }
      if (MinimumTimestampOrBound != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MinimumTimestampOrBound);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OutputStreamRuntimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.StreamName.Length != 0) {
        StreamName = other.StreamName;
      }
      if (other.NumberOfPacketsAdded != 0) {
        NumberOfPacketsAdded = other.NumberOfPacketsAdded;
      }
      if (other.MinimumTimestampOrBound != 0L) {
        MinimumTimestampOrBound = other.MinimumTimestampOrBound;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StreamName = input.ReadString();
            break;
          }
          case 16: {
            NumberOfPacketsAdded = input.ReadInt32();
            break;
          }
          case 24: {
            MinimumTimestampOrBound = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StreamName = input.ReadString();
            break;
          }
          case 16: {
            NumberOfPacketsAdded = input.ReadInt32();
            break;
          }
          case 24: {
            MinimumTimestampOrBound = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The runtime info for a calculator.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CalculatorRuntimeInfo : pb::IMessage<CalculatorRuntimeInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CalculatorRuntimeInfo> _parser = new pb::MessageParser<CalculatorRuntimeInfo>(() => new CalculatorRuntimeInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CalculatorRuntimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GraphRuntimeInfoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculatorRuntimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculatorRuntimeInfo(CalculatorRuntimeInfo other) : this() {
      calculatorName_ = other.calculatorName_;
      lastProcessStartUnixUs_ = other.lastProcessStartUnixUs_;
      lastProcessFinishUnixUs_ = other.lastProcessFinishUnixUs_;
      timestampBound_ = other.timestampBound_;
      inputStreamInfos_ = other.inputStreamInfos_.Clone();
      outputStreamInfos_ = other.outputStreamInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculatorRuntimeInfo Clone() {
      return new CalculatorRuntimeInfo(this);
    }

    /// <summary>Field number for the "calculator_name" field.</summary>
    public const int CalculatorNameFieldNumber = 1;
    private string calculatorName_ = "";
    /// <summary>
    /// The name of the calculator.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CalculatorName {
      get { return calculatorName_; }
      set {
        calculatorName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_process_start_unix_us" field.</summary>
    public const int LastProcessStartUnixUsFieldNumber = 2;
    private long lastProcessStartUnixUs_;
    /// <summary>
    /// The last time when the Calculator::Process was started.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastProcessStartUnixUs {
      get { return lastProcessStartUnixUs_; }
      set {
        lastProcessStartUnixUs_ = value;
      }
    }

    /// <summary>Field number for the "last_process_finish_unix_us" field.</summary>
    public const int LastProcessFinishUnixUsFieldNumber = 3;
    private long lastProcessFinishUnixUs_;
    /// <summary>
    /// The last time when the Calculator::Process was finished.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastProcessFinishUnixUs {
      get { return lastProcessFinishUnixUs_; }
      set {
        lastProcessFinishUnixUs_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_bound" field.</summary>
    public const int TimestampBoundFieldNumber = 4;
    private long timestampBound_;
    /// <summary>
    /// The timestamp bound of the calculator.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimestampBound {
      get { return timestampBound_; }
      set {
        timestampBound_ = value;
      }
    }

    /// <summary>Field number for the "input_stream_infos" field.</summary>
    public const int InputStreamInfosFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Mediapipe.InputStreamRuntimeInfo> _repeated_inputStreamInfos_codec
        = pb::FieldCodec.ForMessage(42, global::Mediapipe.InputStreamRuntimeInfo.Parser);
    private readonly pbc::RepeatedField<global::Mediapipe.InputStreamRuntimeInfo> inputStreamInfos_ = new pbc::RepeatedField<global::Mediapipe.InputStreamRuntimeInfo>();
    /// <summary>
    /// The runtime info for each input stream of the calculator.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Mediapipe.InputStreamRuntimeInfo> InputStreamInfos {
      get { return inputStreamInfos_; }
    }

    /// <summary>Field number for the "output_stream_infos" field.</summary>
    public const int OutputStreamInfosFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Mediapipe.OutputStreamRuntimeInfo> _repeated_outputStreamInfos_codec
        = pb::FieldCodec.ForMessage(50, global::Mediapipe.OutputStreamRuntimeInfo.Parser);
    private readonly pbc::RepeatedField<global::Mediapipe.OutputStreamRuntimeInfo> outputStreamInfos_ = new pbc::RepeatedField<global::Mediapipe.OutputStreamRuntimeInfo>();
    /// <summary>
    /// The runtime info for each output stream of the calculator.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Mediapipe.OutputStreamRuntimeInfo> OutputStreamInfos {
      get { return outputStreamInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CalculatorRuntimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CalculatorRuntimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CalculatorName != other.CalculatorName) return false;
      if (LastProcessStartUnixUs != other.LastProcessStartUnixUs) return false;
      if (LastProcessFinishUnixUs != other.LastProcessFinishUnixUs) return false;
      if (TimestampBound != other.TimestampBound) return false;
      if(!inputStreamInfos_.Equals(other.inputStreamInfos_)) return false;
      if(!outputStreamInfos_.Equals(other.outputStreamInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CalculatorName.Length != 0) hash ^= CalculatorName.GetHashCode();
      if (LastProcessStartUnixUs != 0L) hash ^= LastProcessStartUnixUs.GetHashCode();
      if (LastProcessFinishUnixUs != 0L) hash ^= LastProcessFinishUnixUs.GetHashCode();
      if (TimestampBound != 0L) hash ^= TimestampBound.GetHashCode();
      hash ^= inputStreamInfos_.GetHashCode();
      hash ^= outputStreamInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CalculatorName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CalculatorName);
      }
      if (LastProcessStartUnixUs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastProcessStartUnixUs);
      }
      if (LastProcessFinishUnixUs != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(LastProcessFinishUnixUs);
      }
      if (TimestampBound != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimestampBound);
      }
      inputStreamInfos_.WriteTo(output, _repeated_inputStreamInfos_codec);
      outputStreamInfos_.WriteTo(output, _repeated_outputStreamInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CalculatorName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CalculatorName);
      }
      if (LastProcessStartUnixUs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastProcessStartUnixUs);
      }
      if (LastProcessFinishUnixUs != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(LastProcessFinishUnixUs);
      }
      if (TimestampBound != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimestampBound);
      }
      inputStreamInfos_.WriteTo(ref output, _repeated_inputStreamInfos_codec);
      outputStreamInfos_.WriteTo(ref output, _repeated_outputStreamInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CalculatorName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CalculatorName);
      }
      if (LastProcessStartUnixUs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastProcessStartUnixUs);
      }
      if (LastProcessFinishUnixUs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastProcessFinishUnixUs);
      }
      if (TimestampBound != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampBound);
      }
      size += inputStreamInfos_.CalculateSize(_repeated_inputStreamInfos_codec);
      size += outputStreamInfos_.CalculateSize(_repeated_outputStreamInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CalculatorRuntimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.CalculatorName.Length != 0) {
        CalculatorName = other.CalculatorName;
      }
      if (other.LastProcessStartUnixUs != 0L) {
        LastProcessStartUnixUs = other.LastProcessStartUnixUs;
      }
      if (other.LastProcessFinishUnixUs != 0L) {
        LastProcessFinishUnixUs = other.LastProcessFinishUnixUs;
      }
      if (other.TimestampBound != 0L) {
        TimestampBound = other.TimestampBound;
      }
      inputStreamInfos_.Add(other.inputStreamInfos_);
      outputStreamInfos_.Add(other.outputStreamInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CalculatorName = input.ReadString();
            break;
          }
          case 16: {
            LastProcessStartUnixUs = input.ReadInt64();
            break;
          }
          case 24: {
            LastProcessFinishUnixUs = input.ReadInt64();
            break;
          }
          case 32: {
            TimestampBound = input.ReadInt64();
            break;
          }
          case 42: {
            inputStreamInfos_.AddEntriesFrom(input, _repeated_inputStreamInfos_codec);
            break;
          }
          case 50: {
            outputStreamInfos_.AddEntriesFrom(input, _repeated_outputStreamInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CalculatorName = input.ReadString();
            break;
          }
          case 16: {
            LastProcessStartUnixUs = input.ReadInt64();
            break;
          }
          case 24: {
            LastProcessFinishUnixUs = input.ReadInt64();
            break;
          }
          case 32: {
            TimestampBound = input.ReadInt64();
            break;
          }
          case 42: {
            inputStreamInfos_.AddEntriesFrom(ref input, _repeated_inputStreamInfos_codec);
            break;
          }
          case 50: {
            outputStreamInfos_.AddEntriesFrom(ref input, _repeated_outputStreamInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The runtime info for the whole graph.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GraphRuntimeInfo : pb::IMessage<GraphRuntimeInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GraphRuntimeInfo> _parser = new pb::MessageParser<GraphRuntimeInfo>(() => new GraphRuntimeInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GraphRuntimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GraphRuntimeInfoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GraphRuntimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GraphRuntimeInfo(GraphRuntimeInfo other) : this() {
      captureTimeUnixUs_ = other.captureTimeUnixUs_;
      calculatorInfos_ = other.calculatorInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GraphRuntimeInfo Clone() {
      return new GraphRuntimeInfo(this);
    }

    /// <summary>Field number for the "capture_time_unix_us" field.</summary>
    public const int CaptureTimeUnixUsFieldNumber = 1;
    private long captureTimeUnixUs_;
    /// <summary>
    /// The time when the runtime info was captured.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CaptureTimeUnixUs {
      get { return captureTimeUnixUs_; }
      set {
        captureTimeUnixUs_ = value;
      }
    }

    /// <summary>Field number for the "calculator_infos" field.</summary>
    public const int CalculatorInfosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mediapipe.CalculatorRuntimeInfo> _repeated_calculatorInfos_codec
        = pb::FieldCodec.ForMessage(18, global::Mediapipe.CalculatorRuntimeInfo.Parser);
    private readonly pbc::RepeatedField<global::Mediapipe.CalculatorRuntimeInfo> calculatorInfos_ = new pbc::RepeatedField<global::Mediapipe.CalculatorRuntimeInfo>();
    /// <summary>
    /// The runtime info for each calculator in the graph.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Mediapipe.CalculatorRuntimeInfo> CalculatorInfos {
      get { return calculatorInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GraphRuntimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GraphRuntimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CaptureTimeUnixUs != other.CaptureTimeUnixUs) return false;
      if(!calculatorInfos_.Equals(other.calculatorInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CaptureTimeUnixUs != 0L) hash ^= CaptureTimeUnixUs.GetHashCode();
      hash ^= calculatorInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CaptureTimeUnixUs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CaptureTimeUnixUs);
      }
      calculatorInfos_.WriteTo(output, _repeated_calculatorInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CaptureTimeUnixUs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CaptureTimeUnixUs);
      }
      calculatorInfos_.WriteTo(ref output, _repeated_calculatorInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CaptureTimeUnixUs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CaptureTimeUnixUs);
      }
      size += calculatorInfos_.CalculateSize(_repeated_calculatorInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GraphRuntimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.CaptureTimeUnixUs != 0L) {
        CaptureTimeUnixUs = other.CaptureTimeUnixUs;
      }
      calculatorInfos_.Add(other.calculatorInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CaptureTimeUnixUs = input.ReadInt64();
            break;
          }
          case 18: {
            calculatorInfos_.AddEntriesFrom(input, _repeated_calculatorInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CaptureTimeUnixUs = input.ReadInt64();
            break;
          }
          case 18: {
            calculatorInfos_.AddEntriesFrom(ref input, _repeated_calculatorInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
