// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: immediate_mux_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from immediate_mux_calculator.proto</summary>
  public static partial class ImmediateMuxCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for immediate_mux_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImmediateMuxCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5pbW1lZGlhdGVfbXV4X2NhbGN1bGF0b3IucHJvdG8SCW1lZGlhcGlwZSJj",
            "Ch1JbW1lZGlhdGVNdXhDYWxjdWxhdG9yT3B0aW9ucxIlChhwcm9jZXNzX3Rp",
            "bWVzdGFtcF9ib3VuZHMYASABKAhIAIgBAUIbChlfcHJvY2Vzc190aW1lc3Rh",
            "bXBfYm91bmRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.ImmediateMuxCalculatorOptions), global::Mediapipe.ImmediateMuxCalculatorOptions.Parser, new[]{ "ProcessTimestampBounds" }, new[]{ "ProcessTimestampBounds" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImmediateMuxCalculatorOptions : pb::IMessage<ImmediateMuxCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImmediateMuxCalculatorOptions> _parser = new pb::MessageParser<ImmediateMuxCalculatorOptions>(() => new ImmediateMuxCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImmediateMuxCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.ImmediateMuxCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImmediateMuxCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImmediateMuxCalculatorOptions(ImmediateMuxCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      processTimestampBounds_ = other.processTimestampBounds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImmediateMuxCalculatorOptions Clone() {
      return new ImmediateMuxCalculatorOptions(this);
    }

    /// <summary>Field number for the "process_timestamp_bounds" field.</summary>
    public const int ProcessTimestampBoundsFieldNumber = 1;
    private readonly static bool ProcessTimestampBoundsDefaultValue = false;

    private bool processTimestampBounds_;
    /// <summary>
    /// Whether to process timestamp bound.
    ///
    /// process_timestamp_bounds = false maintains legacy behavior, where the
    /// calculator will not process timestamp bounds updates for one of the input
    /// streams if input streams > 1 and ImmediateInputStreamHandler is used. e.g.
    /// if input stream 0 receives timestamp bound update to 100, and then input
    /// stream 1 receives a real packet at 90, the packet at 90 will still be sent
    /// out. However, it's not recommended to update timestamp bounds in this case,
    /// since it can lead to undeterministic behavior.
    ///
    /// With process_timestamp_bounds = true, the calculator will maintain a more
    /// stable behavior with timestamp bound updates: It will propagate the
    /// timestamp bound update inputs downstream and increase the input timestamp
    /// bound correspondingly, and drop later packets with smaller input
    /// timestamps.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ProcessTimestampBounds {
      get { if ((_hasBits0 & 1) != 0) { return processTimestampBounds_; } else { return ProcessTimestampBoundsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        processTimestampBounds_ = value;
      }
    }
    /// <summary>Gets whether the "process_timestamp_bounds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProcessTimestampBounds {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "process_timestamp_bounds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProcessTimestampBounds() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImmediateMuxCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImmediateMuxCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProcessTimestampBounds != other.ProcessTimestampBounds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasProcessTimestampBounds) hash ^= ProcessTimestampBounds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasProcessTimestampBounds) {
        output.WriteRawTag(8);
        output.WriteBool(ProcessTimestampBounds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasProcessTimestampBounds) {
        output.WriteRawTag(8);
        output.WriteBool(ProcessTimestampBounds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasProcessTimestampBounds) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImmediateMuxCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasProcessTimestampBounds) {
        ProcessTimestampBounds = other.ProcessTimestampBounds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProcessTimestampBounds = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProcessTimestampBounds = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
