// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packages/com.datea83.mediapipefordots/Runtime/Gpu/gl_animation_overlay_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from Packages/com.datea83.mediapipefordots/Runtime/Gpu/gl_animation_overlay_calculator.proto</summary>
  public static partial class GlAnimationOverlayCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Packages/com.datea83.mediapipefordots/Runtime/Gpu/gl_animation_overlay_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GlAnimationOverlayCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CldQYWNrYWdlcy9jb20uZGF0ZWE4My5tZWRpYXBpcGVmb3Jkb3RzL1J1bnRp",
            "bWUvR3B1L2dsX2FuaW1hdGlvbl9vdmVybGF5X2NhbGN1bGF0b3IucHJvdG8S",
            "CW1lZGlhcGlwZRpIUGFja2FnZXMvY29tLmRhdGVhODMubWVkaWFwaXBlZm9y",
            "ZG90cy9SdW50aW1lL0ZyYW1ld29yay9jYWxjdWxhdG9yLnByb3RvIqoCCiNH",
            "bEFuaW1hdGlvbk92ZXJsYXlDYWxjdWxhdG9yT3B0aW9ucxIaCgxhc3BlY3Rf",
            "cmF0aW8YASABKAI6BDAuNzUSIAoUdmVydGljYWxfZm92X2RlZ3JlZXMYAiAB",
            "KAI6AjcwEiIKFXpfY2xpcHBpbmdfcGxhbmVfbmVhchgDIAEoAjoDMC4xEiIK",
            "FHpfY2xpcHBpbmdfcGxhbmVfZmFyGAQgASgCOgQxMDAwEh8KE2FuaW1hdGlv",
            "bl9zcGVlZF9mcHMYBSABKAI6AjI1MlwKA2V4dBIcLm1lZGlhcGlwZS5DYWxj",
            "dWxhdG9yT3B0aW9ucxj9xKpTIAEoCzIuLm1lZGlhcGlwZS5HbEFuaW1hdGlv",
            "bk92ZXJsYXlDYWxjdWxhdG9yT3B0aW9ucw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.GlAnimationOverlayCalculatorOptions), global::Mediapipe.GlAnimationOverlayCalculatorOptions.Parser, new[]{ "AspectRatio", "VerticalFovDegrees", "ZClippingPlaneNear", "ZClippingPlaneFar", "AnimationSpeedFps" }, null, null, new pb::Extension[] { global::Mediapipe.GlAnimationOverlayCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GlAnimationOverlayCalculatorOptions : pb::IMessage<GlAnimationOverlayCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GlAnimationOverlayCalculatorOptions> _parser = new pb::MessageParser<GlAnimationOverlayCalculatorOptions>(() => new GlAnimationOverlayCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GlAnimationOverlayCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.GlAnimationOverlayCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GlAnimationOverlayCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GlAnimationOverlayCalculatorOptions(GlAnimationOverlayCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      aspectRatio_ = other.aspectRatio_;
      verticalFovDegrees_ = other.verticalFovDegrees_;
      zClippingPlaneNear_ = other.zClippingPlaneNear_;
      zClippingPlaneFar_ = other.zClippingPlaneFar_;
      animationSpeedFps_ = other.animationSpeedFps_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GlAnimationOverlayCalculatorOptions Clone() {
      return new GlAnimationOverlayCalculatorOptions(this);
    }

    /// <summary>Field number for the "aspect_ratio" field.</summary>
    public const int AspectRatioFieldNumber = 1;
    private readonly static float AspectRatioDefaultValue = 0.75F;

    private float aspectRatio_;
    /// <summary>
    /// Default aspect ratio of rendering target width over height.
    /// This specific value is for 3:4 view. Do not change this default value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AspectRatio {
      get { if ((_hasBits0 & 1) != 0) { return aspectRatio_; } else { return AspectRatioDefaultValue; } }
      set {
        _hasBits0 |= 1;
        aspectRatio_ = value;
      }
    }
    /// <summary>Gets whether the "aspect_ratio" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAspectRatio {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "aspect_ratio" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAspectRatio() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "vertical_fov_degrees" field.</summary>
    public const int VerticalFovDegreesFieldNumber = 2;
    private readonly static float VerticalFovDegreesDefaultValue = 70F;

    private float verticalFovDegrees_;
    /// <summary>
    /// Default vertical field of view in degrees. This specific default value
    /// is arbitrary. Do not change this default value. If you want to use
    /// a different vertical_fov_degrees, set it in the options.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VerticalFovDegrees {
      get { if ((_hasBits0 & 2) != 0) { return verticalFovDegrees_; } else { return VerticalFovDegreesDefaultValue; } }
      set {
        _hasBits0 |= 2;
        verticalFovDegrees_ = value;
      }
    }
    /// <summary>Gets whether the "vertical_fov_degrees" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVerticalFovDegrees {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "vertical_fov_degrees" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVerticalFovDegrees() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "z_clipping_plane_near" field.</summary>
    public const int ZClippingPlaneNearFieldNumber = 3;
    private readonly static float ZClippingPlaneNearDefaultValue = 0.1F;

    private float zClippingPlaneNear_;
    /// <summary>
    /// Perspective projection matrix z-clipping near plane value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ZClippingPlaneNear {
      get { if ((_hasBits0 & 4) != 0) { return zClippingPlaneNear_; } else { return ZClippingPlaneNearDefaultValue; } }
      set {
        _hasBits0 |= 4;
        zClippingPlaneNear_ = value;
      }
    }
    /// <summary>Gets whether the "z_clipping_plane_near" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasZClippingPlaneNear {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "z_clipping_plane_near" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearZClippingPlaneNear() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "z_clipping_plane_far" field.</summary>
    public const int ZClippingPlaneFarFieldNumber = 4;
    private readonly static float ZClippingPlaneFarDefaultValue = 1000F;

    private float zClippingPlaneFar_;
    /// <summary>
    /// Perspective projection matrix z-clipping far plane value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ZClippingPlaneFar {
      get { if ((_hasBits0 & 8) != 0) { return zClippingPlaneFar_; } else { return ZClippingPlaneFarDefaultValue; } }
      set {
        _hasBits0 |= 8;
        zClippingPlaneFar_ = value;
      }
    }
    /// <summary>Gets whether the "z_clipping_plane_far" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasZClippingPlaneFar {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "z_clipping_plane_far" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearZClippingPlaneFar() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "animation_speed_fps" field.</summary>
    public const int AnimationSpeedFpsFieldNumber = 5;
    private readonly static float AnimationSpeedFpsDefaultValue = 25F;

    private float animationSpeedFps_;
    /// <summary>
    /// Speed at which to play the animation (in frames per second).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AnimationSpeedFps {
      get { if ((_hasBits0 & 16) != 0) { return animationSpeedFps_; } else { return AnimationSpeedFpsDefaultValue; } }
      set {
        _hasBits0 |= 16;
        animationSpeedFps_ = value;
      }
    }
    /// <summary>Gets whether the "animation_speed_fps" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnimationSpeedFps {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "animation_speed_fps" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnimationSpeedFps() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GlAnimationOverlayCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GlAnimationOverlayCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AspectRatio, other.AspectRatio)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VerticalFovDegrees, other.VerticalFovDegrees)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ZClippingPlaneNear, other.ZClippingPlaneNear)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ZClippingPlaneFar, other.ZClippingPlaneFar)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AnimationSpeedFps, other.AnimationSpeedFps)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAspectRatio) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AspectRatio);
      if (HasVerticalFovDegrees) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VerticalFovDegrees);
      if (HasZClippingPlaneNear) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ZClippingPlaneNear);
      if (HasZClippingPlaneFar) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ZClippingPlaneFar);
      if (HasAnimationSpeedFps) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AnimationSpeedFps);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAspectRatio) {
        output.WriteRawTag(13);
        output.WriteFloat(AspectRatio);
      }
      if (HasVerticalFovDegrees) {
        output.WriteRawTag(21);
        output.WriteFloat(VerticalFovDegrees);
      }
      if (HasZClippingPlaneNear) {
        output.WriteRawTag(29);
        output.WriteFloat(ZClippingPlaneNear);
      }
      if (HasZClippingPlaneFar) {
        output.WriteRawTag(37);
        output.WriteFloat(ZClippingPlaneFar);
      }
      if (HasAnimationSpeedFps) {
        output.WriteRawTag(45);
        output.WriteFloat(AnimationSpeedFps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAspectRatio) {
        output.WriteRawTag(13);
        output.WriteFloat(AspectRatio);
      }
      if (HasVerticalFovDegrees) {
        output.WriteRawTag(21);
        output.WriteFloat(VerticalFovDegrees);
      }
      if (HasZClippingPlaneNear) {
        output.WriteRawTag(29);
        output.WriteFloat(ZClippingPlaneNear);
      }
      if (HasZClippingPlaneFar) {
        output.WriteRawTag(37);
        output.WriteFloat(ZClippingPlaneFar);
      }
      if (HasAnimationSpeedFps) {
        output.WriteRawTag(45);
        output.WriteFloat(AnimationSpeedFps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAspectRatio) {
        size += 1 + 4;
      }
      if (HasVerticalFovDegrees) {
        size += 1 + 4;
      }
      if (HasZClippingPlaneNear) {
        size += 1 + 4;
      }
      if (HasZClippingPlaneFar) {
        size += 1 + 4;
      }
      if (HasAnimationSpeedFps) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GlAnimationOverlayCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasAspectRatio) {
        AspectRatio = other.AspectRatio;
      }
      if (other.HasVerticalFovDegrees) {
        VerticalFovDegrees = other.VerticalFovDegrees;
      }
      if (other.HasZClippingPlaneNear) {
        ZClippingPlaneNear = other.ZClippingPlaneNear;
      }
      if (other.HasZClippingPlaneFar) {
        ZClippingPlaneFar = other.ZClippingPlaneFar;
      }
      if (other.HasAnimationSpeedFps) {
        AnimationSpeedFps = other.AnimationSpeedFps;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            AspectRatio = input.ReadFloat();
            break;
          }
          case 21: {
            VerticalFovDegrees = input.ReadFloat();
            break;
          }
          case 29: {
            ZClippingPlaneNear = input.ReadFloat();
            break;
          }
          case 37: {
            ZClippingPlaneFar = input.ReadFloat();
            break;
          }
          case 45: {
            AnimationSpeedFps = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            AspectRatio = input.ReadFloat();
            break;
          }
          case 21: {
            VerticalFovDegrees = input.ReadFloat();
            break;
          }
          case 29: {
            ZClippingPlaneNear = input.ReadFloat();
            break;
          }
          case 37: {
            ZClippingPlaneFar = input.ReadFloat();
            break;
          }
          case 45: {
            AnimationSpeedFps = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the GlAnimationOverlayCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.GlAnimationOverlayCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.GlAnimationOverlayCalculatorOptions>(174760573, pb::FieldCodec.ForMessage(1398084586, global::Mediapipe.GlAnimationOverlayCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
