// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: resample_time_series_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from resample_time_series_calculator.proto</summary>
  public static partial class ResampleTimeSeriesCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for resample_time_series_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResampleTimeSeriesCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVyZXNhbXBsZV90aW1lX3Nlcmllc19jYWxjdWxhdG9yLnByb3RvEgltZWRp",
            "YXBpcGUaEGNhbGN1bGF0b3IucHJvdG8ikQcKI1Jlc2FtcGxlVGltZVNlcmll",
            "c0NhbGN1bGF0b3JPcHRpb25zEhoKEnRhcmdldF9zYW1wbGVfcmF0ZRgBIAEo",
            "ARJvCg5yZXNhbXBsZXJfdHlwZRgCIAEoDjI8Lm1lZGlhcGlwZS5SZXNhbXBs",
            "ZVRpbWVTZXJpZXNDYWxjdWxhdG9yT3B0aW9ucy5SZXNhbXBsZXJUeXBlOhlS",
            "RVNBTVBMRVJfUkFUSU9OQUxfRkFDVE9SEnEKHXJlc2FtcGxlcl9saWJyZXNh",
            "bXBsZV9vcHRpb25zGAMgASgLMkoubWVkaWFwaXBlLlJlc2FtcGxlVGltZVNl",
            "cmllc0NhbGN1bGF0b3JPcHRpb25zLlJlc2FtcGxlckxpYlJlc2FtcGxlT3B0",
            "aW9ucxJ4CiFyZXNhbXBsZXJfcmF0aW9uYWxfZmFjdG9yX29wdGlvbnMYBCAB",
            "KAsyTS5tZWRpYXBpcGUuUmVzYW1wbGVUaW1lU2VyaWVzQ2FsY3VsYXRvck9w",
            "dGlvbnMuUmVzYW1wbGVyUmF0aW9uYWxGYWN0b3JPcHRpb25zEisKHWNoZWNr",
            "X2luY29uc2lzdGVudF90aW1lc3RhbXBzGAUgASgIOgR0cnVlEh4KEGFsbG93",
            "X3Vwc2FtcGxpbmcYBiABKAg6BHRydWUSIQoWbWluX3NvdXJjZV9zYW1wbGVf",
            "cmF0ZRgHIAEoAToBMBpIChtSZXNhbXBsZXJMaWJSZXNhbXBsZU9wdGlvbnMS",
            "KQoadXNlX2hpZ2hfcXVhbGl0eV9yZXNhbXBsZXIYASABKAg6BWZhbHNlGpIB",
            "Ch5SZXNhbXBsZXJSYXRpb25hbEZhY3Rvck9wdGlvbnMSGAoNcmFkaXVzX2Zh",
            "Y3RvchgEIAEoAToBNRIeChFjdXRvZmZfcHJvcG9ydGlvbhgFIAEoAToDMC45",
            "EhYKC2thaXNlcl9iZXRhGAMgASgBOgE2Eg4KBnJhZGl1cxgBIAEoARIOCgZj",
            "dXRvZmYYAiABKAEiQwoNUmVzYW1wbGVyVHlwZRINCglVTkRFRklORUQQABId",
            "ChlSRVNBTVBMRVJfUkFUSU9OQUxfRkFDVE9SEAIiBAgBEAEyXAoDZXh0Ehwu",
            "bWVkaWFwaXBlLkNhbGN1bGF0b3JPcHRpb25zGIfqwBcgASgLMi4ubWVkaWFw",
            "aXBlLlJlc2FtcGxlVGltZVNlcmllc0NhbGN1bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.ResampleTimeSeriesCalculatorOptions), global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Parser, new[]{ "TargetSampleRate", "ResamplerType", "ResamplerLibresampleOptions", "ResamplerRationalFactorOptions", "CheckInconsistentTimestamps", "AllowUpsampling", "MinSourceSampleRate" }, null, new[]{ typeof(global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType) }, new pb::Extension[] { global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Extensions.Ext }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions), global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions.Parser, new[]{ "UseHighQualityResampler" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions), global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions.Parser, new[]{ "RadiusFactor", "CutoffProportion", "KaiserBeta", "Radius", "Cutoff" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResampleTimeSeriesCalculatorOptions : pb::IMessage<ResampleTimeSeriesCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResampleTimeSeriesCalculatorOptions> _parser = new pb::MessageParser<ResampleTimeSeriesCalculatorOptions>(() => new ResampleTimeSeriesCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResampleTimeSeriesCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.ResampleTimeSeriesCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleTimeSeriesCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleTimeSeriesCalculatorOptions(ResampleTimeSeriesCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      targetSampleRate_ = other.targetSampleRate_;
      resamplerType_ = other.resamplerType_;
      resamplerLibresampleOptions_ = other.resamplerLibresampleOptions_ != null ? other.resamplerLibresampleOptions_.Clone() : null;
      resamplerRationalFactorOptions_ = other.resamplerRationalFactorOptions_ != null ? other.resamplerRationalFactorOptions_.Clone() : null;
      checkInconsistentTimestamps_ = other.checkInconsistentTimestamps_;
      allowUpsampling_ = other.allowUpsampling_;
      minSourceSampleRate_ = other.minSourceSampleRate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleTimeSeriesCalculatorOptions Clone() {
      return new ResampleTimeSeriesCalculatorOptions(this);
    }

    /// <summary>Field number for the "target_sample_rate" field.</summary>
    public const int TargetSampleRateFieldNumber = 1;
    private readonly static double TargetSampleRateDefaultValue = 0D;

    private double targetSampleRate_;
    /// <summary>
    /// target_sample_rate is the sample rate, in Hertz, of the output
    /// stream.  Required.  Must be greater than 0.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TargetSampleRate {
      get { if ((_hasBits0 & 1) != 0) { return targetSampleRate_; } else { return TargetSampleRateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        targetSampleRate_ = value;
      }
    }
    /// <summary>Gets whether the "target_sample_rate" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTargetSampleRate {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "target_sample_rate" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTargetSampleRate() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "resampler_type" field.</summary>
    public const int ResamplerTypeFieldNumber = 2;
    private readonly static global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType ResamplerTypeDefaultValue = global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType.ResamplerRationalFactor;

    private global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType resamplerType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType ResamplerType {
      get { if ((_hasBits0 & 2) != 0) { return resamplerType_; } else { return ResamplerTypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        resamplerType_ = value;
      }
    }
    /// <summary>Gets whether the "resampler_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResamplerType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "resampler_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResamplerType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "resampler_libresample_options" field.</summary>
    public const int ResamplerLibresampleOptionsFieldNumber = 3;
    private global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions resamplerLibresampleOptions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions ResamplerLibresampleOptions {
      get { return resamplerLibresampleOptions_; }
      set {
        resamplerLibresampleOptions_ = value;
      }
    }

    /// <summary>Field number for the "resampler_rational_factor_options" field.</summary>
    public const int ResamplerRationalFactorOptionsFieldNumber = 4;
    private global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions resamplerRationalFactorOptions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions ResamplerRationalFactorOptions {
      get { return resamplerRationalFactorOptions_; }
      set {
        resamplerRationalFactorOptions_ = value;
      }
    }

    /// <summary>Field number for the "check_inconsistent_timestamps" field.</summary>
    public const int CheckInconsistentTimestampsFieldNumber = 5;
    private readonly static bool CheckInconsistentTimestampsDefaultValue = true;

    private bool checkInconsistentTimestamps_;
    /// <summary>
    /// Set to false to disable checks for jitter in timestamp values. Useful with
    /// live audio input.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CheckInconsistentTimestamps {
      get { if ((_hasBits0 & 4) != 0) { return checkInconsistentTimestamps_; } else { return CheckInconsistentTimestampsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        checkInconsistentTimestamps_ = value;
      }
    }
    /// <summary>Gets whether the "check_inconsistent_timestamps" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCheckInconsistentTimestamps {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "check_inconsistent_timestamps" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCheckInconsistentTimestamps() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "allow_upsampling" field.</summary>
    public const int AllowUpsamplingFieldNumber = 6;
    private readonly static bool AllowUpsamplingDefaultValue = true;

    private bool allowUpsampling_;
    /// <summary>
    /// Set to false to throw an error if the original audio has lower sample rate
    /// than `target_sample_rate`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowUpsampling {
      get { if ((_hasBits0 & 8) != 0) { return allowUpsampling_; } else { return AllowUpsamplingDefaultValue; } }
      set {
        _hasBits0 |= 8;
        allowUpsampling_ = value;
      }
    }
    /// <summary>Gets whether the "allow_upsampling" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowUpsampling {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "allow_upsampling" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowUpsampling() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "min_source_sample_rate" field.</summary>
    public const int MinSourceSampleRateFieldNumber = 7;
    private readonly static double MinSourceSampleRateDefaultValue = 0D;

    private double minSourceSampleRate_;
    /// <summary>
    /// min_source_sample_rate is the minimum allowed sample rate of the input
    /// stream, in Hertz. Only used when allow_upsampling is set to true.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MinSourceSampleRate {
      get { if ((_hasBits0 & 16) != 0) { return minSourceSampleRate_; } else { return MinSourceSampleRateDefaultValue; } }
      set {
        _hasBits0 |= 16;
        minSourceSampleRate_ = value;
      }
    }
    /// <summary>Gets whether the "min_source_sample_rate" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMinSourceSampleRate {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "min_source_sample_rate" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMinSourceSampleRate() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResampleTimeSeriesCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResampleTimeSeriesCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TargetSampleRate, other.TargetSampleRate)) return false;
      if (ResamplerType != other.ResamplerType) return false;
      if (!object.Equals(ResamplerLibresampleOptions, other.ResamplerLibresampleOptions)) return false;
      if (!object.Equals(ResamplerRationalFactorOptions, other.ResamplerRationalFactorOptions)) return false;
      if (CheckInconsistentTimestamps != other.CheckInconsistentTimestamps) return false;
      if (AllowUpsampling != other.AllowUpsampling) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MinSourceSampleRate, other.MinSourceSampleRate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasTargetSampleRate) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TargetSampleRate);
      if (HasResamplerType) hash ^= ResamplerType.GetHashCode();
      if (resamplerLibresampleOptions_ != null) hash ^= ResamplerLibresampleOptions.GetHashCode();
      if (resamplerRationalFactorOptions_ != null) hash ^= ResamplerRationalFactorOptions.GetHashCode();
      if (HasCheckInconsistentTimestamps) hash ^= CheckInconsistentTimestamps.GetHashCode();
      if (HasAllowUpsampling) hash ^= AllowUpsampling.GetHashCode();
      if (HasMinSourceSampleRate) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MinSourceSampleRate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasTargetSampleRate) {
        output.WriteRawTag(9);
        output.WriteDouble(TargetSampleRate);
      }
      if (HasResamplerType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResamplerType);
      }
      if (resamplerLibresampleOptions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ResamplerLibresampleOptions);
      }
      if (resamplerRationalFactorOptions_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ResamplerRationalFactorOptions);
      }
      if (HasCheckInconsistentTimestamps) {
        output.WriteRawTag(40);
        output.WriteBool(CheckInconsistentTimestamps);
      }
      if (HasAllowUpsampling) {
        output.WriteRawTag(48);
        output.WriteBool(AllowUpsampling);
      }
      if (HasMinSourceSampleRate) {
        output.WriteRawTag(57);
        output.WriteDouble(MinSourceSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasTargetSampleRate) {
        output.WriteRawTag(9);
        output.WriteDouble(TargetSampleRate);
      }
      if (HasResamplerType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResamplerType);
      }
      if (resamplerLibresampleOptions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ResamplerLibresampleOptions);
      }
      if (resamplerRationalFactorOptions_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ResamplerRationalFactorOptions);
      }
      if (HasCheckInconsistentTimestamps) {
        output.WriteRawTag(40);
        output.WriteBool(CheckInconsistentTimestamps);
      }
      if (HasAllowUpsampling) {
        output.WriteRawTag(48);
        output.WriteBool(AllowUpsampling);
      }
      if (HasMinSourceSampleRate) {
        output.WriteRawTag(57);
        output.WriteDouble(MinSourceSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasTargetSampleRate) {
        size += 1 + 8;
      }
      if (HasResamplerType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResamplerType);
      }
      if (resamplerLibresampleOptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResamplerLibresampleOptions);
      }
      if (resamplerRationalFactorOptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResamplerRationalFactorOptions);
      }
      if (HasCheckInconsistentTimestamps) {
        size += 1 + 1;
      }
      if (HasAllowUpsampling) {
        size += 1 + 1;
      }
      if (HasMinSourceSampleRate) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResampleTimeSeriesCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasTargetSampleRate) {
        TargetSampleRate = other.TargetSampleRate;
      }
      if (other.HasResamplerType) {
        ResamplerType = other.ResamplerType;
      }
      if (other.resamplerLibresampleOptions_ != null) {
        if (resamplerLibresampleOptions_ == null) {
          ResamplerLibresampleOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions();
        }
        ResamplerLibresampleOptions.MergeFrom(other.ResamplerLibresampleOptions);
      }
      if (other.resamplerRationalFactorOptions_ != null) {
        if (resamplerRationalFactorOptions_ == null) {
          ResamplerRationalFactorOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions();
        }
        ResamplerRationalFactorOptions.MergeFrom(other.ResamplerRationalFactorOptions);
      }
      if (other.HasCheckInconsistentTimestamps) {
        CheckInconsistentTimestamps = other.CheckInconsistentTimestamps;
      }
      if (other.HasAllowUpsampling) {
        AllowUpsampling = other.AllowUpsampling;
      }
      if (other.HasMinSourceSampleRate) {
        MinSourceSampleRate = other.MinSourceSampleRate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TargetSampleRate = input.ReadDouble();
            break;
          }
          case 16: {
            ResamplerType = (global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType) input.ReadEnum();
            break;
          }
          case 26: {
            if (resamplerLibresampleOptions_ == null) {
              ResamplerLibresampleOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions();
            }
            input.ReadMessage(ResamplerLibresampleOptions);
            break;
          }
          case 34: {
            if (resamplerRationalFactorOptions_ == null) {
              ResamplerRationalFactorOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions();
            }
            input.ReadMessage(ResamplerRationalFactorOptions);
            break;
          }
          case 40: {
            CheckInconsistentTimestamps = input.ReadBool();
            break;
          }
          case 48: {
            AllowUpsampling = input.ReadBool();
            break;
          }
          case 57: {
            MinSourceSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TargetSampleRate = input.ReadDouble();
            break;
          }
          case 16: {
            ResamplerType = (global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerType) input.ReadEnum();
            break;
          }
          case 26: {
            if (resamplerLibresampleOptions_ == null) {
              ResamplerLibresampleOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerLibResampleOptions();
            }
            input.ReadMessage(ResamplerLibresampleOptions);
            break;
          }
          case 34: {
            if (resamplerRationalFactorOptions_ == null) {
              ResamplerRationalFactorOptions = new global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Types.ResamplerRationalFactorOptions();
            }
            input.ReadMessage(ResamplerRationalFactorOptions);
            break;
          }
          case 40: {
            CheckInconsistentTimestamps = input.ReadBool();
            break;
          }
          case 48: {
            AllowUpsampling = input.ReadBool();
            break;
          }
          case 57: {
            MinSourceSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ResampleTimeSeriesCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResamplerType {
        [pbr::OriginalName("UNDEFINED")] Undefined = 0,
        /// <summary>
        /// RESAMPLER_RATIONAL_FACTOR selects QResampler which
        /// replaces RationalFactorResampler.
        /// </summary>
        [pbr::OriginalName("RESAMPLER_RATIONAL_FACTOR")] ResamplerRationalFactor = 2,
      }

      /// <summary>
      /// Parameters for initializing LibResampleResampler. See LibResampleResampler
      /// for more details.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ResamplerLibResampleOptions : pb::IMessage<ResamplerLibResampleOptions>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ResamplerLibResampleOptions> _parser = new pb::MessageParser<ResamplerLibResampleOptions>(() => new ResamplerLibResampleOptions());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ResamplerLibResampleOptions> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerLibResampleOptions() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerLibResampleOptions(ResamplerLibResampleOptions other) : this() {
          _hasBits0 = other._hasBits0;
          useHighQualityResampler_ = other.useHighQualityResampler_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerLibResampleOptions Clone() {
          return new ResamplerLibResampleOptions(this);
        }

        /// <summary>Field number for the "use_high_quality_resampler" field.</summary>
        public const int UseHighQualityResamplerFieldNumber = 1;
        private readonly static bool UseHighQualityResamplerDefaultValue = false;

        private bool useHighQualityResampler_;
        /// <summary>
        /// Whether to use libresample's high-quality resampling mode.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool UseHighQualityResampler {
          get { if ((_hasBits0 & 1) != 0) { return useHighQualityResampler_; } else { return UseHighQualityResamplerDefaultValue; } }
          set {
            _hasBits0 |= 1;
            useHighQualityResampler_ = value;
          }
        }
        /// <summary>Gets whether the "use_high_quality_resampler" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasUseHighQualityResampler {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "use_high_quality_resampler" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearUseHighQualityResampler() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ResamplerLibResampleOptions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ResamplerLibResampleOptions other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UseHighQualityResampler != other.UseHighQualityResampler) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasUseHighQualityResampler) hash ^= UseHighQualityResampler.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasUseHighQualityResampler) {
            output.WriteRawTag(8);
            output.WriteBool(UseHighQualityResampler);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasUseHighQualityResampler) {
            output.WriteRawTag(8);
            output.WriteBool(UseHighQualityResampler);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasUseHighQualityResampler) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ResamplerLibResampleOptions other) {
          if (other == null) {
            return;
          }
          if (other.HasUseHighQualityResampler) {
            UseHighQualityResampler = other.UseHighQualityResampler;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UseHighQualityResampler = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UseHighQualityResampler = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Parameters for initializing the RationalFactorResampler. See
      /// RationalFactorResampler for more details.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ResamplerRationalFactorOptions : pb::IMessage<ResamplerRationalFactorOptions>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ResamplerRationalFactorOptions> _parser = new pb::MessageParser<ResamplerRationalFactorOptions>(() => new ResamplerRationalFactorOptions());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ResamplerRationalFactorOptions> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerRationalFactorOptions() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerRationalFactorOptions(ResamplerRationalFactorOptions other) : this() {
          _hasBits0 = other._hasBits0;
          radiusFactor_ = other.radiusFactor_;
          cutoffProportion_ = other.cutoffProportion_;
          kaiserBeta_ = other.kaiserBeta_;
          radius_ = other.radius_;
          cutoff_ = other.cutoff_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ResamplerRationalFactorOptions Clone() {
          return new ResamplerRationalFactorOptions(this);
        }

        /// <summary>Field number for the "radius_factor" field.</summary>
        public const int RadiusFactorFieldNumber = 4;
        private readonly static double RadiusFactorDefaultValue = 5D;

        private double radiusFactor_;
        /// <summary>
        /// Scale factor for the resampling kernel's nonzero support radius. If
        /// upsampling, the kernel radius is `filter_radius_factor` input samples. If
        /// downsampling, the kernel radius is `filter_radius_factor` *output*
        /// samples. Larger radius makes the transition between passband and stopband
        /// sharper, but proportionally increases computation and memory cost.
        ///
        /// The default value 5.0 corresponds to libresample's "low quality" mode
        /// (which despite the name, is quite good quality).
        ///
        /// A value of 17.0 corresponds to libresample's "high quality" mode.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double RadiusFactor {
          get { if ((_hasBits0 & 8) != 0) { return radiusFactor_; } else { return RadiusFactorDefaultValue; } }
          set {
            _hasBits0 |= 8;
            radiusFactor_ = value;
          }
        }
        /// <summary>Gets whether the "radius_factor" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasRadiusFactor {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "radius_factor" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearRadiusFactor() {
          _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "cutoff_proportion" field.</summary>
        public const int CutoffProportionFieldNumber = 5;
        private readonly static double CutoffProportionDefaultValue = 0.9D;

        private double cutoffProportion_;
        /// <summary>
        /// Antialiasing cutoff frequency as a proportion of
        ///   min(input_sample_rate, output_sample_rate) / 2.
        /// The default is 0.9, meaning the cutoff is at 90% of the input Nyquist
        /// frequency or the output Nyquist frequency, whichever is smaller.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double CutoffProportion {
          get { if ((_hasBits0 & 16) != 0) { return cutoffProportion_; } else { return CutoffProportionDefaultValue; } }
          set {
            _hasBits0 |= 16;
            cutoffProportion_ = value;
          }
        }
        /// <summary>Gets whether the "cutoff_proportion" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCutoffProportion {
          get { return (_hasBits0 & 16) != 0; }
        }
        /// <summary>Clears the value of the "cutoff_proportion" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCutoffProportion() {
          _hasBits0 &= ~16;
        }

        /// <summary>Field number for the "kaiser_beta" field.</summary>
        public const int KaiserBetaFieldNumber = 3;
        private readonly static double KaiserBetaDefaultValue = 6D;

        private double kaiserBeta_;
        /// <summary>
        /// The Kaiser beta parameter for the kernel window. A larger value implies
        /// wider transistion band and stronger stopband attenuation.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double KaiserBeta {
          get { if ((_hasBits0 & 4) != 0) { return kaiserBeta_; } else { return KaiserBetaDefaultValue; } }
          set {
            _hasBits0 |= 4;
            kaiserBeta_ = value;
          }
        }
        /// <summary>Gets whether the "kaiser_beta" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasKaiserBeta {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "kaiser_beta" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearKaiserBeta() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "radius" field.</summary>
        public const int RadiusFieldNumber = 1;
        private readonly static double RadiusDefaultValue = 0D;

        private double radius_;
        /// <summary>
        /// Kernel radius in units of input samples. It is related to radius_factor
        /// by radius_factor = radius * min(1, output_rate / input_rate).
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Radius {
          get { if ((_hasBits0 & 1) != 0) { return radius_; } else { return RadiusDefaultValue; } }
          set {
            _hasBits0 |= 1;
            radius_ = value;
          }
        }
        /// <summary>Gets whether the "radius" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasRadius {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "radius" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearRadius() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "cutoff" field.</summary>
        public const int CutoffFieldNumber = 2;
        private readonly static double CutoffDefaultValue = 0D;

        private double cutoff_;
        /// <summary>
        /// Anti-aliasing cutoff frequency in Hertz. A reasonable setting is
        /// 0.45 * min(input_rate, output_rate). It is related to cutoff_proportion
        /// by cutoff_proportion = 2 * cutoff / min(output_rate, input_rate).
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Cutoff {
          get { if ((_hasBits0 & 2) != 0) { return cutoff_; } else { return CutoffDefaultValue; } }
          set {
            _hasBits0 |= 2;
            cutoff_ = value;
          }
        }
        /// <summary>Gets whether the "cutoff" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCutoff {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "cutoff" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCutoff() {
          _hasBits0 &= ~2;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ResamplerRationalFactorOptions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ResamplerRationalFactorOptions other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RadiusFactor, other.RadiusFactor)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CutoffProportion, other.CutoffProportion)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(KaiserBeta, other.KaiserBeta)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Radius, other.Radius)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Cutoff, other.Cutoff)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasRadiusFactor) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RadiusFactor);
          if (HasCutoffProportion) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CutoffProportion);
          if (HasKaiserBeta) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(KaiserBeta);
          if (HasRadius) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Radius);
          if (HasCutoff) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Cutoff);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasRadius) {
            output.WriteRawTag(9);
            output.WriteDouble(Radius);
          }
          if (HasCutoff) {
            output.WriteRawTag(17);
            output.WriteDouble(Cutoff);
          }
          if (HasKaiserBeta) {
            output.WriteRawTag(25);
            output.WriteDouble(KaiserBeta);
          }
          if (HasRadiusFactor) {
            output.WriteRawTag(33);
            output.WriteDouble(RadiusFactor);
          }
          if (HasCutoffProportion) {
            output.WriteRawTag(41);
            output.WriteDouble(CutoffProportion);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasRadius) {
            output.WriteRawTag(9);
            output.WriteDouble(Radius);
          }
          if (HasCutoff) {
            output.WriteRawTag(17);
            output.WriteDouble(Cutoff);
          }
          if (HasKaiserBeta) {
            output.WriteRawTag(25);
            output.WriteDouble(KaiserBeta);
          }
          if (HasRadiusFactor) {
            output.WriteRawTag(33);
            output.WriteDouble(RadiusFactor);
          }
          if (HasCutoffProportion) {
            output.WriteRawTag(41);
            output.WriteDouble(CutoffProportion);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasRadiusFactor) {
            size += 1 + 8;
          }
          if (HasCutoffProportion) {
            size += 1 + 8;
          }
          if (HasKaiserBeta) {
            size += 1 + 8;
          }
          if (HasRadius) {
            size += 1 + 8;
          }
          if (HasCutoff) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ResamplerRationalFactorOptions other) {
          if (other == null) {
            return;
          }
          if (other.HasRadiusFactor) {
            RadiusFactor = other.RadiusFactor;
          }
          if (other.HasCutoffProportion) {
            CutoffProportion = other.CutoffProportion;
          }
          if (other.HasKaiserBeta) {
            KaiserBeta = other.KaiserBeta;
          }
          if (other.HasRadius) {
            Radius = other.Radius;
          }
          if (other.HasCutoff) {
            Cutoff = other.Cutoff;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                Radius = input.ReadDouble();
                break;
              }
              case 17: {
                Cutoff = input.ReadDouble();
                break;
              }
              case 25: {
                KaiserBeta = input.ReadDouble();
                break;
              }
              case 33: {
                RadiusFactor = input.ReadDouble();
                break;
              }
              case 41: {
                CutoffProportion = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 9: {
                Radius = input.ReadDouble();
                break;
              }
              case 17: {
                Cutoff = input.ReadDouble();
                break;
              }
              case 25: {
                KaiserBeta = input.ReadDouble();
                break;
              }
              case 33: {
                RadiusFactor = input.ReadDouble();
                break;
              }
              case 41: {
                CutoffProportion = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the ResampleTimeSeriesCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.ResampleTimeSeriesCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.ResampleTimeSeriesCalculatorOptions>(49296647, pb::FieldCodec.ForMessage(394373178, global::Mediapipe.ResampleTimeSeriesCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
